### ISSUE TITLE
Configure GitHub Repository

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#1]
### Tasks 
- [x] Create a milestone for each iteration
- [x] Establish rules for PR review/approval before merging to main branch
- [x] Invite every member as a collaborator

**Comment by WillTrem** [comment]
Basic  setup of the repository has been done
