### ISSUE TITLE
[US] Scheduled Activities

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#100]
As an application user, I want to view and manage scheduled activities of the database from the application to better track their execution and easily make adjustments to their schedules if need be.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should      | Low                   |    5 |

## Acceptance Criteria
- A "Scheduled Activities" menu should be accessible from the settings page
- Already existing scheduled activities should be displayed
- For each scheduled activity, 
    - A schedule editor box should be visible to be able to make changes to the schedule on which the activity runs. (Could be either a text editor for CRON or a fancier, more user-friendly menu)
    - A list of execution logs of the scheduled activity should be visible, each log containing
        - The date-time of the execution
        - The duration of the execution
        - The output/result of the activity's execution

## Risks
- Modifying schedules by mistake from the CRON syntax, which may cause undesired behaviors
## Tasks
- [x] Fetch all stored procedures (hard coded at the moment but will be able to fetch them when completed)
- [x] Fetch current schedule jobs corresponding to selected procedure and display in table
- [x] Fetch past logs for currently selected procedure

## Notes
This story is dependent on the completion of story #98, as it is pg_cron that enables the scheduled activities functionality.

**Comment by tsitirides** [comment]
https://github.com/WillTrem/UInnovate/assets/47327032/58c1ae15-761a-43c2-a334-e2b78e94ae9c

**Comment by tsitirides** [comment]
Note: scheduling does not work as there is no way to run commands from the VMD and I ran out of time trying to figure out what was going on with the permissions to the cron table. Can be pushed to next sprint, but shouldn't take too long either

**Comment by TheOrangeDuke** [comment]
Looks good to me. 
Please comment with ticket number for the "update cron schedule" part of the ticket. 
Signing off the current work.

**Comment by GuardiansAscend** [comment]
there is still a PR open for this story, please make sure those issues are resolved before this can be closed
