### ISSUE TITLE
[US] Business Logic JavaScript Editor

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#101]
As an application configurator, I want to write some simple javascript, so that it can be later used to incorporate some business logic into the application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could have | Low                     | 8                    |

## Acceptance Criteria
- Have a new pane in the settings associated with "scripting" 
- In that menu, a list of existing scripts should be displayed
- There should be the possibility of creating new scripts
- In that pane, a small javascript editor allows to modify the javascript code
- The scripts should be stored in the database and loaded in the settings as needed

## Risks
- Modifications of the scripts on storage/load

## Tasks
- [x] Confirm any doubts about the story with the stakeholder
- [x] UI Mockups for the "scripting" settings menu
- [x] Add Scripting Tab to the settings menu
- [x] Create a scripts table in the database
- [x] Add the scripts list and implement the adding script logic
- [x] Add the Javascript Editor to the tab
- [x] Add the frontend for script-table association

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/4eb2e15d-8ce0-4871-864d-b084591e9ec2

**Comment by TheOrangeDuke** [comment]
Looks good to me!
Nice work!
Signing off.
