### ISSUE TITLE
[US] Business Logic Script Button 

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#103]
As an application user, I want to press a button from a table's view, so that I have the confirmation that a business logic script will be executed.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could have |      Low                | 3                   |

## Acceptance Criteria
- On any given table's view, a button should be present for each business logic script associated to that table
    - Should think about the cases where multiple scripts are associated to a single table. 
- When pressing the button, a confirmation modal should be displayed, showing:
    - The current action
    - Its description
    - Buttons to confirm/cancel executing the action 

## Risks
- More dependencies on the VMD
- Decreased consistency in the user interface styling

## Tasks
- [x] Add the button as well as its handle Click function
- [x] Make sure that the UI looks adequate with multiple buttons
- [x] Create a Popup modal to let the user execute the script

## Notes
- This story is dependent on story #102

**Comment by SamRfk** [comment]
User story is related to PR #194

**Comment by TheOrangeDuke** [comment]
Looks good! Signing Off!
