### ISSUE TITLE
[US] Environment Variables

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#105]
As a application configurator, I want to configure app-wide environment variables, so that they can be used elsewhere in the application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could have | Low                      |                    5|

## Acceptance Criteria
- In the scripting tab of the settings page, a menu specific for environment variables should be accessible
- In that menu, a list of key/value pairs of the existing environment variables should be visible
- Already existing variables can be modified
- New variables can be added
- Variables are stored/retrieved to/from the database as required

## Risks
- Exposing secrets

## Tasks
- [x] Clarifying any doubts with the stakeholder 
- [x] Create ability to add a new env var and sync with db
- [x] Create ability to modify an existing env var and update its value in the db

 ## Notes 
- This story is dependent on #101 regarding the UI layout, as well as all the other business-logic sidecar related stories.

**Comment by Alexicazana** [comment]
### Initial "Add a new environment variable" button created: 
![Screenshot 2023-12-04 at 8 20 34 PM](https://github.com/WillTrem/UInnovate/assets/55753055/bff3aa50-ee8a-417e-92b4-1776c8fafe1f)

**Comment by Alexicazana** [comment]
### Pop up rendered with editable fields for the environment var name and value (as per requirements):
![Screenshot 2023-12-04 at 8 20 41 PM](https://github.com/WillTrem/UInnovate/assets/55753055/e023970e-a121-4d87-a9d5-cd50ea8e8fd7)

**Comment by Alexicazana** [comment]
Moved env var creator inside Scripting tag:
![Screenshot 2023-12-04 at 8 25 38 PM](https://github.com/WillTrem/UInnovate/assets/55753055/9c9ee166-3ae1-41de-b45e-ba47066a51de)

**Comment by Alexicazana** [comment]
### Finally managed to fix the adding a new row to the db successfully:

![Uploading Screenshot 2023-12-04 at 9.24.01 PM.png…]()

**Comment by Alexicazana** [comment]
### Finally managed to fix the adding a new row to the db successfully:
![Screenshot 2023-12-04 at 9 24 01 PM](https://github.com/WillTrem/UInnovate/assets/55753055/91ed350f-a6e7-4208-a3ba-54bd4a4b4708)

**Comment by Alexicazana** [comment]
### Create editing feature to update existing env variable
Bug: text fields aren't editable for some reason

![Screenshot 2023-12-04 at 11 11 00 PM](https://github.com/WillTrem/UInnovate/assets/55753055/6f4475f7-a977-49a8-8d06-846d0ef3c4f6)
![Screenshot 2023-12-04 at 11 11 12 PM](https://github.com/WillTrem/UInnovate/assets/55753055/aa06b723-8dc8-4111-a85f-89d53a04d58d)

**Comment by Alexicazana** [comment]
https://github.com/WillTrem/UInnovate/assets/55753055/8561f911-c5df-473a-8561-11c44f2f8ea9

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!

**Comment by GuardiansAscend** [comment]
update here when you are able to add those tests you mentioned in the demo vid, and then we can close this

**Comment by Alexicazana** [comment]
Finally managed to fix the bug for modifying existing variables, and refactored the code for this story so that it's cleaner and more cohesive

**Comment by Alexicazana** [comment]
Updated UI for having a separate tab for environment variables as required + Adding a new env var behaviour syncs correctly

![Screenshot 2024-01-26 at 4 00 02 PM](https://github.com/WillTrem/UInnovate/assets/55753055/ef6ce953-dfb6-46e7-a837-97c76d2307ba)
![Screenshot 2024-01-26 at 4 00 40 PM](https://github.com/WillTrem/UInnovate/assets/55753055/95176adf-9209-42a4-8f5e-96c05b6d48b8)
![Screenshot 2024-01-26 at 4 02 14 PM](https://github.com/WillTrem/UInnovate/assets/55753055/ddd80d8a-b8e2-4a92-85a3-4f842bb6f250)

**Comment by Alexicazana** [comment]
Modifying an existing environment variable:
- The UI correctly saves the new state of the modified variable without defaulting back to the old value after exiting the editor:
![Screenshot 2024-01-26 at 4 08 28 PM](https://github.com/WillTrem/UInnovate/assets/55753055/748b3705-e7c4-4ba8-af98-88f7227b7443)
![Screenshot 2024-01-26 at 4 08 33 PM](https://github.com/WillTrem/UInnovate/assets/55753055/fde4a014-cb12-48dc-a0e6-bc0ff51299ec)



- The database correctly changes the value of the variable, without failing and without swapping the order of the variables by recently created date (buggy behaviour):

![Screenshot 2024-01-26 at 4 10 30 PM](https://github.com/WillTrem/UInnovate/assets/55753055/da95be55-7ebf-4cb0-8d0b-cf1299c6f58c)

**Comment by lyubageorgieva** [comment]
This US is pushed to Iteration 9, since we are missing the demo video, as our Stakeholder requested to keep doing the videos for sign-off.

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
