### ISSUE TITLE
[US] Logo and Company Name Creation

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#107]
As a stakeholder, I want to have a proper website and logo, so that I can showcase my product via a brand name/image to my users.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |               Low       |           2         |

## Acceptance Criteria
- Showcase the creation to your stakeholder and get it approved
- Ability to have a memorable name/logo for the product

## Risks
No risks

## Tasks
- [x] Research about a proper logo reference
- [x] Sketch on Procreate, and draw the official outline
- [x] Convert the PNG to SVG in Adobe Illustrator
- [x] Get it approved by the stakeholder

## Note
US #90 is dependent on this US, hence it needs to be completed first.

**Comment by lyubageorgieva** [comment]
## Preview of PostGOAT 
![PostGOAT](https://github.com/WillTrem/UInnovate/assets/74876532/18a66d41-236a-470d-ad3b-4bd40fbe4161)

## To note
There is no need to create a US video because the Image is self-explanatory

**Comment by lyubageorgieva** [comment]
## Logo to SVG
_Could be improved with better quality for a future iteration_
![postGOAT](https://github.com/WillTrem/UInnovate/assets/74876532/7f1970a2-1e9b-44f5-a3a1-695f06d07f5a)
