### ISSUE TITLE
[US] Root Menu Front-end

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#11]
As an application user, when I load the app, I want to have a root menu displayed so that I can see all the tables from the application.

| MoSCoW      | Risk               | Story Points  |
| ------------- | ------------- | ------------- |
|      Must       |        L          |       5           |

## Acceptance Criteria
-  On application load, the user is shown a root menu
- The root menu contains all the application tables that the database contains
## Risks
None
## Tasks
- [x] #25
- [x] Setup all the needed dependencies for our project 
- [x] Update the Readme about how to configure and launch the React App
- [x] Create the front-end of the root menu, using a UI library
- [x] Fetch all the existing databases to be presented on the root menu
- [x] Set up unit tests

**Comment by MariaR001** [comment]
![ArchitectureSOEN490- US #11  Root menu front end](https://github.com/WillTrem/UInnovate/assets/78176331/a32665dd-5c60-4ff4-8474-84f5aaa2df8e)

**Comment by SamRfk** [comment]
Naive implementation of the Object Menu:

| ObjectMenu.tsx |
|-|
|![image](https://github.com/WillTrem/UInnovate/assets/78221579/168b9385-74fe-4f97-a5ce-5dc42470401f)|

**Comment by lyubageorgieva** [comment]
## Demo Video Part 1 
Regarding Tasks:
- Create the React App

- Setup all the needed dependencies for our project
-  Update the Readme about how to configure and launch the React App

https://github.com/WillTrem/UInnovate/assets/74876532/0e6248a2-698d-4756-b880-43e34d0fe56a

**Comment by MariaR001** [comment]
## Demo Video Part 2 
Regarding Tasks:
- Implement UI unit tests
- Architecture diagram for root menu
- Additional tasks done: implement component, e2e and report coverage

https://github.com/WillTrem/UInnovate/assets/78176331/549a735c-4a2f-4ea6-9bfa-74abb237b172

**Comment by MaximeJoanisse** [comment]
### Demo Video Part 3 
Regarding Tasks:




- Creating the Frontend component with a navbar and dynamic web page package
- Fetching from the database using VMD to allow table names and their components to be shown

https://github.com/WillTrem/UInnovate/assets/92006009/56c20d12-df71-4eea-9337-7bada34f8e86

**Comment by TheOrangeDuke** [comment]
This looks good. Signing this story off.
