### ISSUE TITLE
[US] Virtual Model Definition Refactoring 

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#110]
As an application configurator, I want to apply different configurations on tables and columns , so that I can set my preferences and needs for better views.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |           Very High |          8          |

## Acceptance Criteria
- New configurations are upserted into the database
- New configurations are loaded onto the VMD for dynamic view
- The Virtual Model Definition fetches schemas/tables/columns upon rendering
- The Virtual Model Definition loads new configs onto the stored schemas 

## Risks
- Module dependencies causing failures with the refactoring
- Testing suite mocks not applying to the new Virtual Model Definition

## Tasks
- [x] Implement table visibility configuration
- [x] Implement table display type configuration
- [x] Implement column visibility configuration
- [x] Implement column display type configuration
- [x] Apply all Virtual Model changes to the entire codebase
- [x] Rewrite the test suite to reflect all new changes

**Comment by SamRfk** [comment]
Linked to PR #109

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/c360b333-bfd2-4c3e-a26d-edaa30e29f6e
