### ISSUE TITLE
[US] Fancy Columns

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#126]
As an application developer, I want to modify the capability of some display fields, so that I can view them in a more semantically meaningful way.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low                     |      13             |

## Acceptance Criteria
- Ability to utilize the display fields 
- Improve the current fields in a more semantically meaningful way.

## Risks
- TBD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- Add the capability to display some fields in a more semantically meaningful way of:
- [x] Number
- [x] Toggle
- [x] Date Picker
- [x] Date/Time Picker
- [x] Phone Number
- [x] Email
- [ ] Currency
- [ ] Multi-line text WYSIWYG editor

**Comment by AfandiM** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/84986555/02ea1144-680f-4cc8-8a2c-027464ad2a2f)

**Comment by AfandiM** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/84986555/0fbdd237-5fcd-4fe4-b7e2-effd14926817)

**Comment by AfandiM** [comment]
https://github.com/WillTrem/UInnovate/assets/84986555/03e95e8f-6ff4-4077-9d02-1af78d0583c9

**Comment by TheOrangeDuke** [comment]
Looks good! Signing Off!
