### ISSUE TITLE
[US] List View Improvements (Pagination/Reordering)

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#129]
As an application developer, I want to handle pagination, filtering, and reordering from the List View, so that I can utilize the List View to its full potential by having the capacity to handle more complex/larger applications.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Medium                     |          4          |

## Acceptance Criteria
- Ability to utilize the pagination in the List View
- Ability to reorder the List View

## Risks
- Complexity building URLs with the VMD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Choose a standard for the UI components used for pagination/filtering/reordering
- [x] Build the necessary URL's with the VMD
- [x] Add pagination to the tables displayed by the list view
- [x] Add reordering to the list view (make it usable)

**Comment by MaximeJoanisse** [comment]
Design for pagination
![image](https://github.com/WillTrem/UInnovate/assets/92006009/e0404b44-a118-445d-b9fa-11f9518b310a)

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/d32909a4-931b-4f36-bdba-4101921e4e61

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
