### ISSUE TITLE
[US] Create PostgREST instance

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#13]
As a platform developer, I want to run a local instance of a PostgREST server, so that I have an API to further develop the platform.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must-have                    |    Medium                 |  1 SP                  |

## Acceptance Criteria

- Ability to run a local PostgREST server instance within a docker container from a docker compose file.

- Having a configuration file for PostgREST to specify the PostgREST database to connect to / use

- Having documentation explaining how to: 
    - Run the PostgREST container
    - Configure the PostgREST instance to connect to a database

## Risks
- Leak of some PostgreSQL database connection information

## Tasks
- [x] Edit the docker compose configuration file to include the PostgREST container
- [x] Connect PostgREST with the PostgreSQL database server
- [x] Add to the README.md steps on how to setup/run PostgREST

**Comment by AfandiM** [comment]
## Architecture Diagram

![image](https://github.com/WillTrem/UInnovate/assets/84986555/c83d5028-96bd-4526-a4f5-3b2a01622167)

**Comment by lyubageorgieva** [comment]
## Demo Video
Coding, Architecture, and Demo all worked on by @AfandiM 

https://github.com/WillTrem/UInnovate/assets/74876532/4284394c-6cc3-44bc-9520-fd3dfed6562d

**Comment by TheOrangeDuke** [comment]
This looks good. Signing this story off.
