### ISSUE TITLE
[US] List View Search Bar

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#130]
As an application developer, I want to have access to a search bar from the List View, so that query the rows and search by specific fields.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |   Medium                   |    5                |

## Acceptance Criteria
- Ability to view a search bar
- Ability to query the rows from the search bar
- Ability to search by specific field (one at a time)

## Risks
- Complexity building URLs with the VMD

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] UI mockup
- [ ] Add a search bar to help query the rows in the list view
- [ ] Search by specific field (one at a time)

## Could Have Task (If there is time)
- Support multi-column filtering

**Comment by lyubageorgieva** [comment]
To be planned for a future milestone, hence it will be closed now and could be re-opened for a future release.

**Comment by lyubageorgieva** [comment]
This will be closed because it's a high level US out of the capstone scope.
