### ISSUE TITLE
[US] (i18n) - Database Tables to Suport i18n

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#131]
As a platform developer, I want tables and a view to support i18n, so that internationalization is supported on the applications.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Low               |    3               |

## Acceptance Criteria
- Successful creation of the meta tables and view (languages, keys, values, and translations)

## Risks
- No apparent Risk

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Research the proper way to utilize i18n 
- [x] Adding 3 tables within the meta schema languages, keys, and values
- [x] Adding a view for translation having id, language(ref), key(ref), and value

**Comment by lyubageorgieva** [comment]
## Preview
![image](https://github.com/WillTrem/UInnovate/assets/74876532/8ff5621b-dc53-408d-8c76-31e165db0739)

**Comment by lyubageorgieva** [comment]
## Demo
to be uploaded soon

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
