### ISSUE TITLE
[US] (i18n) Key-Value Editor

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#132]
As an application developer, I want to have access to an editor for i18n, so that view/edit/configure the key-value from the labels based on the languages supported.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Low                    |  3                  |

## Acceptance Criteria
- Ability to view the Key-Value editor

## Risks
- Adding Complexity to the VMD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] UI mockup
- [x] Create a key-value editor to view/edit/configure the labels

## Disclaimer this US will only include the front-end. The logic will be included for the next iteration as a new US

Related to PR #157

**Comment by lyubageorgieva** [comment]
## UI Mockup
<img width="1223" alt="Screenshot 2023-12-26 at 12 16 07 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/f8c8976e-d008-46c5-af6d-373943882a64">

**Comment by lyubageorgieva** [comment]
## Preview 
<img width="995" alt="Screenshot 2023-12-30 at 1 38 18 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/91eaa244-fcc9-49fa-a516-3e3222e19604">

**Comment by lyubageorgieva** [comment]
## Demo Video
to be uploaded soon

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
