### ISSUE TITLE
[US] (i18n) Support Adding Languages Spontaneously

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#133]
As an application developer, I want to have the ability to add languages spontaneously, so that I can accommodate and offer quick support for my users in terms of internationalization.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Low                    |  2                 |

## Acceptance Criteria
- Ability to successfully add a language spontaneously 

## Risks
- No risk

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] "Add new language" button
- [x] Modal opening and containing a dropdown with possible languages

## Disclaimer this US will only include the front-end. The logic will be included for the next iteration as a new US

Related to PR #157

**Comment by lyubageorgieva** [comment]
## UI Mockup

<img width="815" alt="Screenshot 2023-12-30 at 1 34 02 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/00e2e7ef-6008-45c7-845b-50b4b95c1631">
83bc18e6-2fed-45ea-ae61-ca9daf4a1608">

**Comment by lyubageorgieva** [comment]
## Preview
<img width="1239" alt="Screenshot 2023-12-30 at 1 27 19 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/0931eec8-a187-433d-9737-4ca02edfc817">
<img width="995" alt="Screenshot 2023-12-30 at 1 35 54 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/1f5344ca-45f6-4285-b800-43d11b151bbf">

**Comment by lyubageorgieva** [comment]
## Demo Video
to be uploaded soon

**Comment by TheOrangeDuke** [comment]
Looks good! Please add a link to the associated logic US. Signing off!

**Comment by lyubageorgieva** [comment]
@TheOrangeDuke The link the the associated logic US [US#168](https://github.com/WillTrem/UInnovate/issues/168)
