### ISSUE TITLE
[US] Integrate User Management System Into DB

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#137]
As a platform developer, I want to have a user management system integrated to the database system and PostgREST that I can use to build the related views on top of.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |    High                  |            8pts        |

## Acceptance Criteria
- All the components from the User Management & Authentication proposal have been properly integrated into the database system
- Lowest access required to sensitive data is enforced
- No password is stored as plaintext
- Functionalities have been tested and work as intended
## Risks
- Manipulation of sensitive information
- Management of access to sensitive information
- Some uncertainty regarding how the final system will work

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Read over carefully the User Management & Authentication proposal (#89 )
- [x] Integrate step by step the different components following the guide provided by PostgREST https://postgrest.org/en/stable/how-tos/sql-user-management.html
- [x] Add any other database components necessary that is specific to our system.

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/22f8c1c9-c68d-4e31-91e3-20ed450a20b9

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
