### ISSUE TITLE
[US] User Management View

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#138]
As an application configurator, I want to see the actual users on my application from the User Management view so that I can manage them.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have | Medium                     |      5              |

## Acceptance Criteria
- The User Management view’s table gets populated with the actual users from the database
- The create new user form actually inserts a row for a user into the database using the function established in the previous story
- Modifications made to the table gets reflected & stored in the database

## Risks
- Management of access to sensitive information
- Uncertainties

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US
- [x] Understand the User Management & Authentication proposal (see #89)

## Tasks
- [x] Implement the logic for:
    - [x] Retrieving the data from the user’s table
    - [x] Adding a new user

## Dependencies
#137

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/a28d5c93-e4c7-498c-a56d-8f1f033e63f8

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
