### ISSUE TITLE
[US] Login View & Logic

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#139]
As an application user, I want to login to the platform to gain access to my corresponding data.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |               7       |         13           |

## Acceptance Criteria
- There is a login view for an application user to enter its credentials into
- The login view is linked to the PostgREST api and calls the appropriate database functions
- Logs in the user successfully
- Handles alternative scenarios successfully
    - Wrong email/password combination
    - No email/password provided
- The roles and schema access for that particular user are correctly applied upon login
- User can log out
- Login view & logout are accessible from the main UI

## Risks
- Manipulation of sensitive information
- Access right management
- Uncertainties

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US
- [x] Understand the User Management & Authentication proposal (see #89)

## Tasks
- [x] Design how a user is marked as logged in within the front end and how the VMD would handle it
- [x] Design the UI for the Login view
- [x] Implement the front-end login view and associated logic

## Dependencies
#137 #138

**Comment by WillTrem** [comment]
## UI Mockups
| Initial signup view | Login view | Signup view | User logged in |
|-|-|-|-|
|![image](https://github.com/WillTrem/UInnovate/assets/64431699/7a90e3f5-f45c-4695-8570-839956c290f3)|![image](https://github.com/WillTrem/UInnovate/assets/64431699/86f94852-b064-4232-85cf-7ef83b2c9b6b)|![image](https://github.com/WillTrem/UInnovate/assets/64431699/fd8da981-a7d8-4f9e-8689-13ced2a04db9)|![image](https://github.com/WillTrem/UInnovate/assets/64431699/86d41a71-5d12-45f1-9cab-30999682c57a)|

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/4d79e4ab-bfe6-4127-b340-f5c37caec9e8

**Comment by TheOrangeDuke** [comment]
Signing off!
