### ISSUE TITLE
[US] UI Cleanup

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#14]
As an application user, I want to modify the color scheme of the light mode theme to have a UI-friendly interface, so that I can align it with our brand's design guidelines and enhance the user experience for our customers.

| MoSCoW      |  Risk               | Story Points  |
| ------------- | ------------- | ------------- |
| Should have                    |   Low                      |  2                  |

## Acceptance Criteria
- Change is reflected on the user's application

## Risks
- Complexity of the color scheme does not fit aesthetically or does not represent a proper light-mode scheme

## Tasks
- [x] The table menu in List View has to be brighter
- [x] The table view (actual table) has a light color scheme (for light-mode)
- [x] Fix the inconsistencies regarding various button styles, input boxes, etc .. to have a consistent convention throughout the application

**Comment by lyubageorgieva** [comment]
This US is to be planned for a future release. 
TBD milestone.

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/df1671ee-c824-4e7d-a92e-89c4c1b82583

**Comment by TheOrangeDuke** [comment]
Looks good to me! 
Signing off.
