### ISSUE TITLE
[US] Login Bypass

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#140]
As a platform developer, I want to bypass the login/authentication mechanism to facilitate the development process. 

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |                      Low |               5     |

## Acceptance Criteria
Authentication & login should be by-passable through an environment variable

## Risks
- Uncertainties

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Design the login bypass mechanism
- [ ] Implement the functionality through an environment variable

## Dependencies
Heavy dependency on #139

**Comment by WillTrem** [comment]
Moved to iteration 8 due to underestimating the amount of work needed for #139

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/244d3194-edb9-4537-9c96-5c742eb2c387

**Comment by TheOrangeDuke** [comment]
Looks good! 
Signing off!
