### ISSUE TITLE
[US] Signup flow

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#141]
As an application user, I want to create an account so that I can log in to the platform afterward.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have | Medium                      |           3       |

## Acceptance Criteria
- Administrator must have “registered” a user prior to its signup from the User Management view
- The login view now accepts email accounts which have been “registered” but not created entirely
- In which case, a user signup flow is presented to the user, containing fields to enter:
    - First Name
    - Last Name
    - Password: 12 characters with 1 uppercase, 1 lowercase, 1 special symbol
    - Password Confirmation
- Validation on those fields is executed
- Upon signup, login is executed

## Risks
- Manipulation of sensitive information
- Access right management
- Uncertainties

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US
- [ ] Read over carefully the User Management & Authentication proposal (see #89)

## Tasks
- [ ] Integrate verification of “registered” yet not fully created accounts from the front-end
- [ ] Edit the login view to integrate the signup flow
- [ ] Integrate the frontend signup with the corresponding database function via the API

## Dependencies
#139 

## Notes
This story is a drop-off candidate for Iteration 8.

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/12b36b61-3e67-4f82-adf6-14b70c9bb75d

**Comment by TheOrangeDuke** [comment]
Looks good! 
Signing off!
