### ISSUE TITLE
[US] Roles View

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#142]
As an application administrator, I want to assign roles to user on a “per-schema” basis from a Role Management view to add a level of granularity within the role system.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |Low                      | 8                    |

## Acceptance Criteria
- Administrators (only) have access to a “Role” Tab within the “Users” settings pane
- A text explaining how role works and what are the different possible roles can be seen at the top of the pane
- A table showing
    - Row: user
    - Colum: Schema
    - Cell: Role selection dropdown
- Upon modifications, the roles should be saved in the database.

## Risks
- Access right management
- Uncertainties

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US
- [x] Understand the User Management & Authentication proposal (see #89)

## Tasks
- [x] Modify the existing mechanism to include a “per-schema” role instead of a role across all schemas
- [x] Design the Role Management view
- [x] Implement the Role Management view
- [x] Ensure only administrators have access to this pane

**Comment by WillTrem** [comment]
## Design Mockups 
### Initial Designs
|||
|-|-|
|![image](https://github.com/WillTrem/UInnovate/assets/64431699/f0dc86a8-7eaf-49df-8a18-a7f2c6821685)|![image](https://github.com/WillTrem/UInnovate/assets/64431699/9a0414ca-2ed3-4968-9235-f336540f82a5)|
|![image](https://github.com/WillTrem/UInnovate/assets/64431699/13918e57-51c8-461a-9fc1-14fe5a86934c)|![image](https://github.com/WillTrem/UInnovate/assets/64431699/9f9074b5-0d01-4167-a051-4f1c42875ba8)|
|![image](https://github.com/WillTrem/UInnovate/assets/64431699/1d20a38e-5806-4ad7-ab6a-02d459f3e41b)|

### Final Design:
![image](https://github.com/WillTrem/UInnovate/assets/64431699/ce4fa2df-6277-44a7-8275-e0c6bded76bb)

**Comment by WillTrem** [comment]
## Demo Video (sorry for the length Eddy 😅)

https://github.com/WillTrem/UInnovate/assets/64431699/fa3d4f95-3085-4040-b892-82a1d48ef6c8

**Comment by TheOrangeDuke** [comment]
it's 7:47, as big as a 747 jet :P 
But looks good! (great, even) 
signing off!
