### ISSUE TITLE
[US] Documentation Deployment

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#143]
As a platform developer, I want to deploy my documentation to the platform’s website automatically so that it remains up to date.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |               Medium       |       8             |

## Acceptance Criteria
- Main Documentation is pushed automatically on the postGOAT repository (website) with every merge to main
- Use case Documentation is pushed to the main documentation via a script (but still executed automatically)
- Documentation is accessible through the platform’s website under the path “/docs”

## Risks
- Uncertainties
- Integration between multiple repositories

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Create workflow file for deployment of the mkdocs to PostGOAT repo
- [x] On any modification of Mkdocs push new documentation to other repo
- [x] Copying usecase documentation to root documentation

**Comment by MariaR001** [comment]
https://github.com/WillTrem/UInnovate/assets/78176331/cf157a12-2f28-4132-9331-bc841e55587b

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
