### ISSUE TITLE
[US] Test Reporting

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#144]
As a platform developer, I want to deploy my test reports to the platform’s website automatically so that it remains up to date.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |              Medium        |       5             |

## Acceptance Criteria
- Test reports are pushed automatically on the postGOAT repository (website) with every merge to main.
- Test reports are accessible from a path of the website (e.g. “/tests”)

## Risks
- Uncertainties
- Integration between multiple repositories

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] create a workflow file to automatically push the test reports to PostGOAT repo

## Dependencies
#143 with how the multiple repositories are updated and synced together with CI/CD.

**Comment by MariaR001** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/78176331/8e91da24-e04c-4783-ad89-93e6511b3ef8)
![image](https://github.com/WillTrem/UInnovate/assets/78176331/1d5f3d23-7aaa-4427-ade2-dfd112a8f4a5)

Same concept of updates as doc deployment in PostGOAT repo. The test reports page still needs more work for better presentation.

**Comment by TheOrangeDuke** [comment]
Signing off!
