### ISSUE TITLE
[US] Website Content

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#145]
As a platform developer, I want my platform’s website to have some descriptive content about the platform to introduce the general public to it.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |         Low             |         5           |

## Acceptance Criteria
- The main website has some content explaining the tool/platform’s:
    - Goal
    - Purpose (why is it different (& better in our opinion) then other alternatives)
    - High level functioning
    - Other relevant information
- Have [PostGOAT website](https://uinnovate.netlify.app) be deployed and usable as expected with the new content

## Risks
- Clean up of [PostGoat repo](https://github.com/MariaR001/PostGOAT) (over 90% of files are useless and need to be deleted, very hard to work in...)
- Truthfulness and relevancy of Information presented.

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Create website content text
- [x] Decide what images we want to include

## Tasks
- [x] Write the content
- [x] Clean up repo to make it legible
- [x] Integrate the website content

**Comment by Alexicazana** [comment]
Push to iteration 8 as per stakeholder's suggestion since we don't have enough + need other things to be set up before doing this so that we may have it automated already when we do write the website content (on mod, recompiles the website so that the new content is integrated).

**Comment by Alexicazana** [comment]
Need to clean up the repo before starting because as it is right now, most of the files (~90%) are not only useless but redundant... this makes it extremely hard to work with, there's a ton of duplicate files with seemingly the same content... 

<img width="1393" alt="Screenshot 2024-02-08 at 9 52 47 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/a078bb17-68e8-4073-b1b4-01e0dc088d75">

**Comment by Alexicazana** [comment]
- Modified postgoat repo landing page (layout, images/media, and text content)

<img width="1440" alt="Screenshot 2024-02-09 at 12 45 06 AM" src="https://github.com/WillTrem/UInnovate/assets/55753055/241ab55c-00fe-41da-bcde-bb009f8b5c06">

**Comment by TheOrangeDuke** [comment]
Look good! Signing off!
