### ISSUE TITLE
[US] Enhance Use Case 2 functionalities 

### ISSUE THREAD

**Issue by witnick** [WillTrem/UInnovate#146]
As a user of the app, I want to enhance the use case 2 functionalities, so that I can update a ticket's information and close a ticket.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |     low                 |         2     |

## Acceptance Criteria
- Use custom buttons feature for extra functionalities
- Have a test suit for the url used for the functionalities

## Tasks
- [x] Add new functionalities as stored procedures
  - [x] Update ticket info/status 
  - [x] Assign ticket to a user
  - [x] Any other functionality found to be desirable (as found by the developer working on this)
- [x] Update ER diagram and port it to diagram.io

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/fa26dbf6-0055-4de1-8af0-9dd9019c3b00

**Comment by TheOrangeDuke** [comment]
Signing off!

**Comment by witnick** [comment]
Uploading US146_updated.mp4…

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/b77d80e5-39f5-45f1-9822-9f391c2d8b27
