### ISSUE TITLE
[US] Usecase Dependency Enabling and Verification

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#147]
As an application developer, I want to make sure the platform can run off of my usecase, so that I can ensure the platform works as I expected.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |           medium           |           5         |

## Acceptance Criteria
All subgroups within the project will be working off of the usecase, and no new errors are caused by this change.

## Risks
Possiblity of need to adapt to the new method of database construction, discussion is needed with all members

## Tasks
- [x] Ensure that Usecase 1 and 2 are functional, and display data as expected in the front-end
- [x] Test Cron job-scheduling, making sure that it runs on the usecases
- [x] Test display view settings, making sure that they adapt to the new schemas
- [x] Test general display configuration, making sure that no unforseen display issues come up
- [x] Test database refresh, export and import scripts, making sure they have the right schemas and file pathing
- [x] Arrange the file structure of the usecase according to standard agreed with the stakeholder (and make the standard known here)

## Dependencies
There is a dependency on user story #92, which needs to be done first to map all the new schemas correctly

## Extra
1 USP has been attributed to @MaximeJoanisse for his work on #154

**Comment by GuardiansAscend** [comment]
The usecase dependency has been long since confirmed, since all the scripts, cron jobs, front-end functionality and file structure has been reviewed and confirmed to be functional. The reason that this user story has just remained open was due to the lingering issue of UI bugs, which are still present at the time of writing. As of now, we have a new "bugs" tag to handle this now, so the need for this story to remain open is no longer present. Please refer to the bug tag in Github Issues to view the current bug backlog (https://github.com/WillTrem/UInnovate/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22). I propose to close this as of now, and to redistribute points from this into bug solving. @TheOrangeDuke.

**Comment by TheOrangeDuke** [comment]
Signing off!
