### ISSUE TITLE
[US] General Clean-up and Testing of Scripts

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#148]
As a platform developer, I want to create a usable file structure for scripting, so that accessing scripts is not a hassle.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |          low            |           2         |

## Acceptance Criteria
All scripts are working properly, the file structure is clean and according to what is expected, and unecessary files are removed.

## Risks
Scripts potentially not working for extended periods of time, but this risk is very low with adequate support

## Tasks
- [x] Change the file structure for all scripting (create a new script folder, put all necessary scripts for the platform in there)
- [x] Make sure all scripts in the folder still work
- [x] Remove the back-up of the old database from the repository
- [x] Move "import_appconfig_from_json" out of the file it is currently in, into meta.sql (which should no longer be in the usecase folders)

**Comment by TheOrangeDuke** [comment]
Signing off!

**Comment by GuardiansAscend** [comment]
https://github.com/WillTrem/UInnovate/assets/61199167/4781ed31-dd26-4f63-a67c-771f0f29c479
