### ISSUE TITLE
[US] PostgREST Test Suite Usecase 2

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#149]
As an application configurator, I want to be able to test the content of the API calls to another usecase, so that I can validate the functionality of the VMD.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |       Low              |        3            |

## Acceptance Criteria
- Ability to test the second Usecase's API

## Risks
- Adding complexity to the VMD

## Pre-requisites
- [x] Follow up with developer of #91 to detemine the test suite in use

## Tasks
- [x] A big exploration of the Usecase 2's generated API, in order to design the Data Accessor URL builders inside the VMD.
- [ ] Complete documentation of the API for use case 2 in Mkdocs.
- [x] Writing tests alongside the current Usecase 2 in the test suite.

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/7193c1a4-ada1-4e11-a9e5-9b19dbcae780

**Comment by TheOrangeDuke** [comment]
Looks good! 
Signing off!
