### ISSUE TITLE
[US] Default Layout selection

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#15]
As an application user, I want to be able to view the default display of widgets application from the available options given by the application (e.g. enum view, list view, etc.), so that I can create a tailored interface that best suits the needs and preferences of our target audience.

| MoSCoW      | Risk               | Story Points  |
| ------------- | ------------- | ------------- |
|   Should  |    Medium                  |  3                 |

## Acceptance Criteria
- User has the option to select a default layout

## Risks
- Technical risk of adding another layer to the virtual model definition

## Tasks
- [x] Create a settings page
- [x] Provide the user with the option to modify the default layout between Enum View, and List View
- [x] UI mockup on Figma
- [x] Use Case Diagram for Layout Selection
- [x] Unit/Component Testing

**Comment by lyubageorgieva** [comment]
## Figma prototype of UI
![image](https://github.com/WillTrem/UInnovate/assets/74876532/2e9c6cf6-3366-414a-93bb-ab193d6e3bbd)

**Comment by lyubageorgieva** [comment]
## Use Case Diagram for Customization of the Default Layout
<img width="543" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/83872318-f571-4d6f-a6b7-bf667161baec">

**Comment by lyubageorgieva** [comment]
## Demo Steps
1. Run the app on localhost 
2. On the top navigation bar, click on "Settings"
3. Select an option from the "Default Layout" section
i. Click on "Save"
ii. Close the Modal

**Comment by lyubageorgieva** [comment]
## Preview of the UI
<img width="954" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/39b00ff2-5351-48e3-bf29-e97d4b47df6d">
<img width="952" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/2d6d68f7-d507-4b7f-a8e2-ebc7b0a1d7a4">

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/84f639d6-8651-4906-af56-b89c5cd3e797

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
