### ISSUE TITLE
[US] Adding List View

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#16]
As an application user, I want to click an item on the root menu, so that the application displays a List View of the data contained in that table (selected root menu item).

| MoSCoW      |  Risk               | Story Points  |
| -------------  | ------------- | ------------- |
| Must                     | Medium                      | 3                   |

## Acceptance Criteria
- Root menu items are clickable
- On click, a list view of the selected table is shown 
- The appropriate data is displayed in the list view
- There is a way to navigate back to the root menu from the list view

## Risks
- Adding complexity to the Virtual Model Definition

## Tasks
- [x] UI prototype
- [x] Use Case diagram
- [x] Dynamic pages for table name
- [x] Sidebar of tables name
- [x] Connect VMD with tableName
- [x] Unit & Component Testing

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/36e80d61-1a5a-43fd-a0d8-c516d0d4d5b1

- Dynamic pages for table name
- Sidebar of table names
- Connect VMD with tableName

**Comment by MariaR001** [comment]
- Unit & component testing

https://github.com/WillTrem/UInnovate/assets/78176331/28e440a4-0ad4-4cfe-b038-a11648007c44

**Comment by MariaR001** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/78176331/42b0c1d0-b840-45e6-b960-c113effb6730)

**Comment by MariaR001** [comment]
![ArchitectureSOEN490- US#16  List view](https://github.com/WillTrem/UInnovate/assets/78176331/bda1cd61-57f2-4199-b303-cfec7dd63b8d)

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
