### ISSUE TITLE
[US] (i18n) Logic for i18n Key-Value Editor & Adding New Languages

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#168]
As an application developer, I want to have access to an editor for i18n, so that view/edit/configure the key-value from the labels based on the languages is supported and I want to have the ability to add languages spontaneously so that I can accommodate and offer quick support for my users in terms of internationalization.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Low                      |                 5   |

## Acceptance Criteria
- Ability to view the Key-Value editor with the values from the database.
- Ability to add a language spontaneously that is reflected on the front-end and the database after clicking on "save".

## Risks
No risk

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Fetch the i18n view from the meta schema to appear on the Internationalization tab
- [x] After opening the "Add Language" Model, the user should be invited to add a language that is reflected to the database.

**Comment by lyubageorgieva** [comment]
Adding the logic to display the i18n_translation view to be displayed onto the front-end
<img width="584" alt="Screenshot 2024-01-12 at 12 17 40 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/de66a982-0be6-44d2-ba33-7e961ede35ce">
<img width="1083" alt="Screenshot 2024-01-12 at 12 18 01 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/d7a929c4-c56c-47b9-ac7e-01a2029e898c">

**Comment by lyubageorgieva** [comment]
Logic to add a new Language via the modal, and the changes to be reflected onto the db and front-end

<img width="813" alt="Screenshot 2024-01-13 at 12 09 35 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/a83be9d5-9e67-42a8-81fb-7c42e1b86760">

New column added dynamically based on the inputs from the model
<img width="578" alt="Screenshot 2024-01-13 at 12 11 12 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/112568cb-3d7a-42e7-ae66-25919d289faf">

Changes reflected to i18n_languages table
<img width="525" alt="Screenshot 2024-01-13 at 12 12 32 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/171cccfa-ad6c-40eb-8180-5d7115f5df5b">

Changes reflected to i18n_translations view
<img width="627" alt="Screenshot 2024-01-13 at 12 12 48 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/009b556e-36e5-4440-93d6-9bed997dee85">

US related to PR #192

**Comment by TheOrangeDuke** [comment]
Signing off!
