### ISSUE TITLE
[US] Stand Alone Details View

### ISSUE THREAD

**Issue by MaximeJoanisse** [WillTrem/UInnovate#170]
As a user , I want to change the settings for the standalone detail view, so that when I click on a row on a view list it changes the entire page to the detail page.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |      medium    |   4   |

## Acceptance Criteria

- Ability to see detail view on a page entirely with all the current functionality. 

## Risks

-Adding to the settings and config.

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] add the settings to allow standalone details as an option 
- [ ] add the operation in the list view to make the whole page different
- [ ] css and moving the page entirely back after closing or saving.

**Comment by MaximeJoanisse** [comment]
Rough design idea
![image](https://github.com/WillTrem/UInnovate/assets/92006009/1862996e-1175-4d85-ac86-d68033aa6143)

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/e12d1895-0994-4222-8eef-9ffce76c781b

**Comment by TheOrangeDuke** [comment]
Signing off.
