### ISSUE TITLE
[US] URL Scheme

### ISSUE THREAD

**Issue by MaximeJoanisse** [WillTrem/UInnovate#171]
As an application developer, I want to see URLs change when I'm using different pages/features so that I can easily share links with others using the same data.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |           medium           |         3           |

## Acceptance Criteria
-URL changes for the list, details, and specific primary key values. 

## Risks
-changes to URLs and config

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] add URL for lists view
- [x] add URL for details view 
- [x] add specific primary keys in the details view

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/584e966e-99e6-46de-bbdb-64b239fa9660

**Comment by MaximeJoanisse** [comment]
Rough Original Design 
![image](https://github.com/WillTrem/UInnovate/assets/92006009/2366ec52-15bc-435a-a322-950e360d0ed2)

**Comment by MaximeJoanisse** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/92006009/441abd54-0947-4efd-9787-79403f8122d9)
Added these routes to the app 

Then using react router dom made it so that when clicking on tables it would update the URL with the table you selected

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
