### ISSUE TITLE
[US] File Support

### ISSUE THREAD

**Issue by AfandiM** [WillTrem/UInnovate#174]
As an application developer, I want to have file support in the tables, so that store and download files to and from the database.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |       Medium          |          10          |

## Acceptance Criteria
- Able to store files in database
- Can download files from database through UI

## Risks
- Security of file sharing and transfer
- Complexity of storage

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Create database schema and table for files
- [ ] Add support for displaying references to files in UI
- [ ] Add support for downloading files from UI
- [ ] Add support for drag and drop files into UI

**Comment by AfandiM** [comment]
https://github.com/WillTrem/UInnovate/assets/84986555/a3e9704d-5e78-49de-ab00-7fb3329abb49

**Comment by TheOrangeDuke** [comment]
Looks great! Signing off!
