### ISSUE TITLE
[US] (i18n) Add/edit/remove labels

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#179]
As an application developer, I want my users to be able to add/edit/remove labels so that the labels only display the relevant information.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |           Low           |        4           |

## Acceptance Criteria
- Ability to add a label
- Ability to edit a label
- Ability to remove a label

## Risks
Adding complexity to the VMD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] UI mockup design
- [x] Use Case Diagram
- [x] Logic to add a label
- [x] Logic to edit an existing label
- [x] Logic to remove labels

**Comment by lyubageorgieva** [comment]
## UI mockup
<img width="883" alt="Screenshot 2024-02-10 at 12 53 17 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/7100d6d2-742f-432d-b9d2-74663ed8e429">

**Comment by lyubageorgieva** [comment]
## Use Case Diagram
<img width="726" alt="Screenshot 2024-02-10 at 12 58 15 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/901bc255-95e2-4ec7-b7fe-ce1bea9b748d">

**Comment by lyubageorgieva** [comment]
## Demo Video 

https://github.com/WillTrem/UInnovate/assets/74876532/4446627f-014b-4a69-b7a0-cdb5687a69c7

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
