### ISSUE TITLE
[US] (i18n) Export/Import I18N configurations

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#180]
As an application configurator, I want users to be able to export application i18n configs to a file and reload application i18n configs from a file so that it's possible to keep/use different configurations.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |        Low              |          3          |

## Acceptance Criteria
- Ability to export to json [STORED PROC]
- Ability to export to json [SHELL SCRIPT]
- Ability to import from json [STORED PROC]
- Ability to import from json [SHELL SCRIPT]

## Risks
TBD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Export application I18N configs to file
- [x] Reload application I18N configs from file

**Comment by lyubageorgieva** [comment]
## Sequence Diagram
<img width="624" alt="Screenshot 2024-02-06 at 11 22 16 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/924b21be-97b3-4b99-96c3-cec6c52a8859">

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/732629eb-c7f7-4999-89dd-6da900c405ed

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
