### ISSUE TITLE
[US] (i18n) All application-level "nameable" entities in the I18N tables

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#181]
As an application developer, I want to find label-less entities, and visually flag them, so that the application configurator knows that they exist within the application and need to be translated.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       low               |         3           |

## Acceptance Criteria
- Add schema names to I18N
- Add table names to I18N
- Add column names to I18N

## Risks
TBD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Add schema names to I18N keys table
- [x] Add table names to I18N keys table
- [x] Add column names to I18N keys table
- [x] Visually flag those "nameable" entities into the I18N

**Comment by lyubageorgieva** [comment]
All nameable entries were added to the i18n_keys table + a new column was added (is_default) to distinguish the default labels from the future ones added by the user

<img width="518" alt="Screenshot 2024-01-12 at 12 20 31 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/527d1f2f-a601-4101-a8b6-3de39ef2bfc6">

And to the i18n_translations view
<img width="584" alt="Screenshot 2024-01-12 at 12 17 40 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/de66a982-0be6-44d2-ba33-7e961ede35ce">

**Comment by lyubageorgieva** [comment]
Additionally, all the default labels from the existing schema tables, table names, and column names needed to be distinguished visually, hence an icon was added on the front-end as a lock.

<img width="1083" alt="Screenshot 2024-01-12 at 12 18 01 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/d7a929c4-c56c-47b9-ac7e-01a2029e898c">

**Comment by lyubageorgieva** [comment]
US is related to PR #185

**Comment by TheOrangeDuke** [comment]
Signing off!
