### ISSUE TITLE
[US] Create, Update and Deactivate Cron Schedules

### ISSUE THREAD

**Issue by tsitirides** [WillTrem/UInnovate#187]
As an application user, I want to be able to modify the scheduling of cron jobs from the UI so that I can customize task execution according to my unique workflow and preferences.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |    Medium                  |        6            |

## Acceptance Criteria
-  user interface allows for the easy and intuitive scheduling and modification of cron jobs.
- Input validation to ensure that the cron syntax entered is correct.
- Inclusion of tooltips explaining cron syntax.

## Risks
- Unauthorized access to scheduling could lead to security vulnerabilities.
- Over-scheduling or poor scheduling can strain system resources.
- Users might set incorrect schedules leading to system inefficiencies or failures.

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Add schedule and un-schedule functions in cron.sql
- [x] Create typescript functions that access and execute the SQL functions
- [x] Implement the use of these functions from within the CronTabsJobs Page
- [x] Add auto-refresh of tables on button click

**Comment by TheOrangeDuke** [comment]
Signing off!

**Comment by tsitirides** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/47327032/6433d91b-1e05-445d-832b-7c642f2b906e)

**Comment by tsitirides** [comment]
### Sequence Diagram
![image](https://github.com/WillTrem/UInnovate/assets/47327032/4cc28545-aab1-498f-955b-a4a8938c3b8c)
