### ISSUE TITLE
[US] Config persistence in the database

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#19]
As an application user/configurator, I want to modify the UI layout by hiding tables from the root menu, show/hide certain columns, change the display type of columns, so that fellow users benefit from the app according to the business requirements.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have | Medium | 8|

## Acceptance Criteria
- Can hide/show tables from the settings page
- Within the list view (or any view?) of a given table, columns can be shown/hidden
- Within any view, can change the display type of certain columns
- Have Settings page that allows application configurator to change view configuration
  - Settings page allows selecting individual tables for configuration purposes
  - Settings page displays all of a table's column (with a dropdown)
  - Selections should be persisted

## Risks
- Additional layer to the Virtual Model Definition
- Uncertainty on how to provide these functionalities to the user
- Additional complexity from view configuration

## Tasks
- [x] UI mockup Figma
- [x] Use Case Diagram
- [x] Adjust the Settings page to be able to select individual tables for configuration purposes
- [x] Adjust the Settings page to display all all of one table's columns
- [x] Make sure that on dropdown-select, the new selection is persisted
- [x] Testing

## Note
**The application configuration part of this user story is tightly related to US #58, highly recommend to coordinate with the relevant developers**

**The UI design of US #63 heavily depends on this story because the front-end feature of the Display type is displayed on the same side panel as this US, which creates the side panel. Hence the front-end of this US needs to be completed first, please coordinate with the assignee of #63 once it is done.**

**Comment by Alexicazana** [comment]
Started the hide/show tables via Settings page:
![Screenshot 2023-10-31 at 6 57 19 PM](https://github.com/WillTrem/UInnovate/assets/55753055/994d3208-9d8b-4250-a059-61fd2b943567)
![Screenshot 2023-10-31 at 6 57 29 PM](https://github.com/WillTrem/UInnovate/assets/55753055/f1b0a64c-7ab1-4d04-b61f-7806807fd297)

**Comment by WillTrem** [comment]
## Display Settings Page Mockups
### Display Settings Page - No Table Selected
![image](https://github.com/WillTrem/UInnovate/assets/64431699/9172fb1a-bd19-4c99-aea8-77afe595a8c2)

### Display Settings Page - Table Selected
![image](https://github.com/WillTrem/UInnovate/assets/64431699/cf68adc8-ed89-47aa-b9b5-c58e529b5a23)

### Display Settings Page - Table Selected and Hidden
![image](https://github.com/WillTrem/UInnovate/assets/64431699/1fceb616-1271-407a-882f-4bb72fdc261e)

**Comment by WillTrem** [comment]
## Demo Video 

Uploading Demo_US_#19 .mp4…

**Comment by WillTrem** [comment]
## Demo Video attempt 2

https://github.com/WillTrem/UInnovate/assets/64431699/df554cb1-31ff-4707-b471-346a4473a4c7

**Comment by TheOrangeDuke** [comment]
Looks great!
Signing off!
