### ISSUE TITLE
[US] Create database views

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#20]
As a platform developer, I want to offer multiple informational database views, so that the front end can have access to views of the tables, columns, and relations of all of the application’s data tables.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Medium | 2                   |

## Acceptance Criteria
- The database contains multiple schemas, including one for the data of the application itself and one for our own database views
- In our custom schema, 3 SQL views should be present:
    - View displaying all the **schemas** of the database
    - View displaying all the **tables** of the database 
    - View displaying all the **columns** of the database, grouped by schema, then table, and mentioning any relation with another column of another table
- One or more script should be written to easily replicate views into the database
## Risks
- No apparent risk
## Tasks
- [ ] Defining the schema for our custom views
- [ ] Defining the schema for application data
- [ ] Write in SQL the "Schema" view
- [ ] Write in SQL the "Tables" view
- [ ] Write in SQL the "Columns" view
- [ ] Write a shell script to be able to replicate the views into the database

**Comment by lyubageorgieva** [comment]
## Architecture Diagram
<img width="550" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/1fca1d1a-7adf-42b7-96e3-7a609d641afc">

**Comment by WillTrem** [comment]
## Demo 
With the contribution of @lyubageorgieva 

https://github.com/WillTrem/UInnovate/assets/64431699/efc8f10d-dc05-4ae5-b8a6-fae3a2015384

**Comment by TheOrangeDuke** [comment]
This looks good. Signing this story off.
