### ISSUE TITLE
[US] Publish Postgoat Image to Dockerhub

### ISSUE THREAD

**Issue by Alexicazana** [WillTrem/UInnovate#206]
After containerizing Postgoat, the frontend of our repo, a Docker image must be published to Dockerhub, allowing application users to use it and customize it.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |          Low            |        3            |

## Acceptance Criteria
- [x] Have a reproducible image build
- [x] Reproducible and fault free container running based off the image
- [x] Publish it to Dockerhub
- [x] Have application users successfully use this image as the base image for their Postgoat service

## Risks
- Being able to develop a docker service that runs on different machines (regardless of setup)

## Pre-requisites
- [x] Ensure docker image builds stack correctly on local

## Tasks
- [x] Ensure CORS policy issue is fixed on Nginx server
- [x] Publish image and tag it
- [x] Test using newly published image and make sure it works as expected! :)

**Comment by WillTrem** [comment]
Adjusted the name of the story as per discussing the matter, the automatization will come in a separate story.

**Comment by Alexicazana** [comment]
Here's the newly published docker image on Docker Hub:
https://hub.docker.com/repository/docker/alexicazana/goat-dock/general

This image can be pulled using:
`docker pull alexicazana/goat-dock`

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
