### ISSUE TITLE
[US] Schema Access Management

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#213]
As an administrator, I want to manage and control the access to application schema's data on a per user basis to prevent users from accessing data they shouldn't have access to.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |            Low          |           5         |

## Acceptance Criteria
- Schema access should be editable from the user management menu
- Schema access should be saved in a distinct table within the database
- Schema access policies should be applied on login, where the system would only show schemas in the navbar that the user has access to.
- 

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements

## Tasks
- [ ] Design the way schema access will be stored in the database
- [ ] Implement schema access control within the user management menu
- [ ] Apply schema access on login

**Comment by WillTrem** [comment]
## Change in Design
Initially, the plan was to store the schemas to which users can access in a separate database table. However, after thinking about it while implementing this story, it made more sense to implement it as an extra column within the `authentication.users` table, which would define the schema access list via an array of strings.

![image](https://github.com/WillTrem/UInnovate/assets/64431699/71cac65e-7cf0-4885-9f92-867136fb8ff2)
*Implementation of the schema access list (shown via the meta.user_info view)*

This makes it easier to manage both on the database and the front-end level, as it would have otherwise required to keep track of database relations from the front end, which adds a level of unnecessary complexity. It also doesn't involve any limitations compared to the database table approach.

**Comment by WillTrem** [comment]
##Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/21100799-b3b8-461c-bf02-7b4edb700a93

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
