### ISSUE TITLE
[US] User Active State

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#214]
As an administrator , I want to control the active state of users on the platform, so that prevent the access to the platform to a user if need be.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |  Low                    |             2       |

## Acceptance Criteria
- Active state per user should be editable through the user management menu
- Upon an edit made to the active state of a user, the change should be updated in the database
- If a user's active state is set to false, the platform should prevent it from logging in.

## Risks
- Disabling access to user 

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements

## Tasks
- [ ] Implement active state management within the user management menu
- [ ] Implement active state verification within the login form
- [ ] Display a clear and descriptive error message on the login form if a user tries to log in with an inactive account.

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/f7f30d3f-e5e8-427b-ab60-eb8cb191a9a4

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
