### ISSUE TITLE
[US] (i18n) Sort tables by missing translations

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#216]
As an application user, I want to be able to sort the i18n table, so that I can see any labels that have missing translations.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       low               |          3          |

## Acceptance Criteria
- Ability to sort the table by missing translations

## Risks
- No risk

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] UI Mockup
- [x] Use Case Diagram
- [x] Add "Show missing translations" button 
- [x] On button click, add the logic to sort the i18n table by missing translations

**Comment by lyubageorgieva** [comment]
# UI mockup

**_Before_ Clicking ``Show Missing Translations``**
<img width="1017" alt="Screenshot 2024-02-01 at 10 48 38 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/61989b45-8c86-42d1-b3ea-ffa319712ac8">

**_After_ Clicking ``Show Missing Translations``**
<img width="1008" alt="Screenshot 2024-02-01 at 10 48 55 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/1c31b3f3-1335-4720-8266-2856afa91c23">

**Comment by lyubageorgieva** [comment]
# Use Case Diagram
<img width="1114" alt="Screenshot 2024-02-01 at 11 00 32 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/63a65f26-c730-4661-ab23-5c36844325c4">

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/0fc1e3ce-aaa0-4ad1-8df7-c002e66e87ad

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
