### ISSUE TITLE
[US] Details View - Split Screen + Refactoring

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#217]
As an application developer, I want to [ do Y ], so that [ I can accomplish Z ].

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |       Medium               |          4          |

## Acceptance Criteria
- Ability to view the Details View as a split-screen besides the List View Tables
- Ability to view the entirety of each table in the List View or as a Look Up table via the scroll bar
- Ability to view the entirety of each modal to add fields

## Risks
- Risk to have to find another split component to use, if the current one is not able to function as a split screen

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] UI mockup
- [ ] Adapt our current split-screen to not act as an overlay but besides the table
- [ ] Refactor our List View tables to have a scroll bar to be able to fit inside of the screen, and with the split screen 
- [ ] Apply the same principle to the Look Up Tables as mentioned previously
- [ ] Refactor also the modals to add a row in the List View to display all the fields by adding a scroll bar 

## Notes
- This US had similar features with BUG an existing bug, hence it was combined and closing this US will help to close #198

**Comment by GuardiansAscend** [comment]
Given that this was mostly a UI suggestion and not an essential feature, I have opted to deprioritize this in favor of more critical user stories
