### ISSUE TITLE
[US] List View - Column-based ordering (ascending/descending on column header click)

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#218]
As an application user, I want to be able to filter the columns of the tables, so that I can customize the filter experience.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |          Low            |        4            |

## Risks
- Performance concerns if the data volume is large
- Complexity if different column require different filtering logic

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [x] Determine the kind of column-filtering for the existing tables
- [x] Remove the dropdown for ordering
- [x] add new table with new columns for ordering

## Note
[Table View: Looks and Feels](https://retool.com/components/table-new)

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/c7c3ad5e-7475-4af5-8eed-2f6ebb82a5e1

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
