### ISSUE TITLE
[US] Change of Link Scheme for objectMenu and Settings

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#219]
As an application developer, I want to see URLs change when I'm using different pages/features so that I can easily share links with others using the same data. This should apply to settings

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       low               |           4         |

## Acceptance Criteria
-URL should allow to go through settings and list/enum view with the schema and tablename in the URL

## Risks
- URL structure

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Make the changes for the list/enum view with the new designs
- [x] Make the changes for the Settings with the URL
- [x] make the changes for the Navbar

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/ed4ab06b-8e57-4b7b-8d8a-2e50f1c03786

includes video for bugs #251 #234 #232

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
