### ISSUE TITLE
[US] Define and Create Use Case

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#22]
As a platform developer, I want to create a well-defined use case with the stakeholder so that we can better illustrate potential needs that application users may have.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should-have | Low | 3 SP |

## Acceptance Criteria
- The requirements expressed by the stakeholder must be respected and met.
## Risks
- Confusion about the requirements set by the stakeholder.
## Tasks
- [x] Meet with the stakeholder to record the requirements they set and make a list of the functionalities for the use case
- [x] Create a structure.sql file that properly reflects the needs of the use case (domain model definition)
- [x] Create a sampledata.sql file for the use case defined (database tables)

**Comment by Alexicazana** [comment]
![IMG_2068](https://github.com/WillTrem/UInnovate/assets/55753055/2b890328-ba8a-47b7-a00c-93502ca06783)

**Comment by GuardiansAscend** [comment]
https://github.com/WillTrem/UInnovate/assets/61199167/528d8ed0-26e8-4bf8-8995-39a13898c7ed

**Comment by TheOrangeDuke** [comment]
Looks good! Signing it off!
