### ISSUE TITLE
[US] Handling Application Logo's

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#220]
As an application configurator, I want to showcase the logo of the current tenant's application, so that the application is represented to the users.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       Low               |         3           |

## Acceptance Criteria
- View Logo + Name of PostGoat on home page (Square Logo)
- View the tenant's logo on the login page (after configs) (Generic Logo)
- View the tenant's logo in the corner of the app
- Ability from the tenant to load a transparent .png that will be scaled and reused properly

## Risks
- no risks

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] In the Settings page, GeneralTab to have edits to allow the tenant to load a transparent .png that will be scaled and reused properly (drop a file) #174 needs to functional
- [ ] Logo + Name of PostGoat displayed on home page
- [ ] Display the tenant's logo on the login page (after configs)
- [ ] Display the tenant's logo in the corner of the app
- [ ] Display PostGOAT icon and name in Index.html to be displayed once the page is loaded on the window

**Comment by GuardiansAscend** [comment]
This story ended up being much more complex than I had previously thought. I had assumed the attachment tables we use for uploading files would have been fine enough to use for this purpose as well, but it turns out that isnt the case, and there would need to be quite a bit of adjustment to the way our file attachments currently work to support this change. I think because of this, this story has fallen out of scope.
