### ISSUE TITLE
[US] File Preview Functionality

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#222]
As an application user, I want to be able to preview a file's contents without having to actively download it, so that I can quickly assess the file's content and decide whether I need to download it for further examination. 

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       Medium               |       5             |

## Acceptance Criteria
- Ability to preview a file's contents without having to actively download it on the user's computer

## Risks
- Security risks such as file format vulnerabilities
- Privacy concerns such as sensitive information exposure

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] UI mockup
- [ ] Identify the types of files supported by the application for file preview
- [ ] Have a mechanism to detect the file
- [ ] TBD
