### ISSUE TITLE
[US] User Action Logging & Tracing

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#223]
As an application configurator, I want to log and trace relevant user actions, so that I can capture user interactions and activities on data pages.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | High | 8 |

## Acceptance Criteria
- Any relevant action done by a user is logged into a table
- Messages are displayed upon success or failure of such actions

## Risks
- Confidential or sensitive information could be leaked 

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements if deemed necessary
- [x] Discuss with the pod how the logging mechanisms would work and arrive to a consensus
- [x] Figure out what actions should be logged and how should they be displayed

## Tasks
- [x] Implement user-facing logging mechanisms for user actions 
- [x] Log user actions with their timestamps and any errors encountered by such action
- [x] Display messages or notifications for operations done (user, role, timestamp, details potentially with primary key, schema and table name)

**Comment by MariaR001** [comment]
UI Mockup
![image](https://github.com/WillTrem/UInnovate/assets/78176331/12c1a346-9d54-4f79-8183-c9cd188f746b)

**Comment by MariaR001** [comment]
https://github.com/WillTrem/UInnovate/assets/78176331/2a423edb-1018-420f-92f8-b8be8f35fe1a

**Comment by TheOrangeDuke** [comment]
Looks great! Signing off!
