### ISSUE TITLE
[US] Settings Page Audit Trail

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#224]
As an application configurator, I want to have an audit log, so that I can track changes made by administrators.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Medium | 8 (could be more) |

## Acceptance Criteria
- Changes made in the settings page are logged
- There is a user interface for admins to check the audit log and go through it

## Risks
- Sensitive information could be exposed

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements if deemed necessary
- [x] Discuss with the pod how the logging mechanisms would work and arrive to a consensus
- [x] Develop a UI mockup of the admin interface for the audit trail

## Tasks
- [x] Develop an audit trail system specific to the settings page
- [x] Log details of the actions made (who made the change, timestamp, nature of the changes)
- [x] Provide an admin-facing UI letting admins review and potentially query (addition story points) the audit trail

**Comment by MariaR001** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/78176331/6a6a5c59-f744-4f52-9396-ffe9b932599d)

**Comment by TheOrangeDuke** [comment]
Looks great! Signing off!
