### ISSUE TITLE
[US] CSV Load-Up Support

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#225]
As an application user, I want to feed data into the system with a CSV file, so that I can populate tables automatically.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | High | 8|

## Acceptance Criteria
- Users can successfully upload a csv file to feed data
- The mapping mechanism successfully maps CSV columns to database fields
- Tables and their respective columns and rows are added to the database 

## Risks
- File upload could be malicious
- Database manipulation could be dangerous

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements if deemed necessary
- [ ] Discuss with the pod to clarify any ambiguity

## Tasks
- [ ] Implement the CSV file upload functionality (only .csv should be allowed, nothing else! consider implementing a maximum upload size too)
- [ ] Create a mapping mechanism that correctly (and generally) maps the csv columns to their corresponding database fields
- [ ] Support the ability to repeat the data load action with the same or different CSV files
- [ ] Use a staging (temporary) table storing the CSV file's data before committing it to the main database tables/schemas
- [ ] Implement proper validation and error handling for the CSV data

**Comment by Alexicazana** [comment]
Need to push back to iteration 12, requires stakeholder collaboration

**Comment by WillTrem** [comment]
Taking over the story as per discussed
