### ISSUE TITLE
[US] Export/Import Custom Scripts

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#226]
As an application configurator, I want to be able to export custom scripts to a file and reload such scripts from a file so that it's possible to keep/use different scripts.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low | 3 |

## Acceptance Criteria
- The configurator can successfully export the script file
- The configurator can successfully reload a script file onto the application

## Risks
- Letting users upload files could lead to injection vulnerabilities

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements if deemed necessary

## Tasks
- [ ] Export custom javascript actions
- [ ] Restore custom javascript actions
