### ISSUE TITLE
[US] Export/Import Environment Variables

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#227]
As an application configurator, I want to be able to export my environment variables to a file and reload such variables from a file so that it's possible to keep/use different env. variables.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low | 2 |

## Acceptance Criteria
- The configurator can successfully export the environment file
- The configurator can successfully reload an environment file onto the application

## Risks
- Letting users upload files could lead to injection vulnerabilities

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements if deemed necessary

## Tasks
- [x] Export environment variables
- [x] Reload environment variables

**Comment by tsitirides** [comment]
### DEMO VID
https://github.com/WillTrem/UInnovate/assets/47327032/68ce5e07-759c-4371-8543-fc70c9800426

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
