### ISSUE TITLE
[US] Calling Stored Procedures from the UI

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#228]
As an application configurator, I want to call stored procedures directly from the user interface so that I can run such procedures more efficiently.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low | 5 |

## Acceptance Criteria
- The configurator can run a stored procedure from the user interface
- A popup is shown to let the user know whether or not the operation was successful

## Risks
- A user without the proper permissions could run malicious procedures
- A user could run resource-taxing procedures, potentially affecting performance

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements if deemed necessary

## Tasks
- [ ] Create a button from the list view of different tables when a row is selected
- [ ] Associate stored procedures to the button so that they run on click, let the user choose which procedure to run
- [ ] Display a popup showing that the operation is successful / has failed

**Comment by tsitirides** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/47327032/9acb967d-6763-4409-be77-acc508c61389)

![image](https://github.com/WillTrem/UInnovate/assets/47327032/ddaa0c77-e3ce-480e-ba8c-87611bf3c1a9)

Execute Procedures works in an extremely similar way to scripts, you can create a procedure button that will be applied to a view.

You can change the button name and description as well as see the function source code (not sure how we feel about this but should be ok for now).

Once the button is added we can navigate to a view and see that button:

![image](https://github.com/WillTrem/UInnovate/assets/47327032/1dde6f5b-0a26-4411-94cf-af695aa1d6ac)
 

When pressed a pop up will prompt you to confirm execution:

![image](https://github.com/WillTrem/UInnovate/assets/47327032/5faee93a-9622-47fb-8c86-b3ca96712f32)


and an alert follows with the status of if the function completed or not:

![image](https://github.com/WillTrem/UInnovate/assets/47327032/0b481b56-e664-499c-9118-95112cfcfc4d)

**Comment by tsitirides** [comment]
https://github.com/WillTrem/UInnovate/assets/47327032/b4703c71-9b6b-4312-a239-e9b536938c54
