### ISSUE TITLE
[US] Adding Custom Views

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#229]
As an application configurator, I want to add additional views so that I can display my tables and data in different ways

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low | 5 |

## Acceptance Criteria
- A user can successfully create a new view

## Risks
- Potentially sensitive data exposure
- Performance impact on having many views

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements if deemed necessary
- [x] UI mockups for the settings tab if necessary

## Tasks
- [x] Create a new tab in the Settings page for additional views
- [x] Create a side menu showing all already existing additional views
- [x] Create a menu letting the user create a new view (the user will have the option between calendar, timeline, and tree-view component for now
- [x] The menu should also ask the user under which schema the view has to be created in

**Comment by SamRfk** [comment]
This story is a prerequisite for US #230

**Comment by witnick** [comment]
Add view prototype
![AdditionalViews-Add-View drawio](https://github.com/WillTrem/UInnovate/assets/10947924/0d13b3c5-5983-4668-9773-95b171ed2dcb)

**Comment by witnick** [comment]
All views prototype
![AdditionalViews-All-views drawio](https://github.com/WillTrem/UInnovate/assets/10947924/5431e9b5-e9f1-4c11-82c0-a53f10d8fbe2)

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/c223ee5f-d991-48b5-9029-32d1fa2125a4

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
