### ISSUE TITLE
[US] Additional Views Navigation

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#230]
As an application configurator, I want to be able to navigate to my views so that I can display them on my screen

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low | 3 |

## Acceptance Criteria
- The user can select and display their additional view from the sub header

## Risks
- Performance impact on having many new views
- User Interface buttons might be hard to place

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements if deemed necessary

## Tasks
- [x] Create a sub header under the main navigation bar (lighter gray shade)
- [x] Display the views associated to the selected schema as buttons
- [x] When clicking on a view, the view's page shows (empty for now)

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/3a053efc-91a4-4d07-a071-2d2dcee10951

**Comment by witnick** [comment]
I changed the style of the buttons and removed the View title 

![additionalview_icons](https://github.com/WillTrem/UInnovate/assets/10947924/75e48436-d99f-46de-b9b7-d85bdc06b073)

**Comment by witnick** [comment]
Quick demo of the additional view navigation in object view
![additionalview](https://github.com/WillTrem/UInnovate/assets/10947924/a08cd69a-baf7-44e6-9d9a-14c13edd27cb)

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/074be4ca-1e4d-4929-b6e1-1bf626ffcafd

**Comment by TheOrangeDuke** [comment]
Looks good
Signing off!
