### ISSUE TITLE
[US] Lookup Table References

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#231]
As a user, I want look-up tables to be bidirectional, so that I can look up any tables that reference or are referenced by the original table.

| MoSCoW      |  Risk               | Story Points  |
| ------------ |------------- | ------------- |
| Must|          medium            |          5          |

## Acceptance Criteria
Tables that reference or are referenced can be looked up
## Risks
adding complexity to look up table's logic 
## Pre-requisites
- [x] Meet with the stakeholders to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] change the meta.sql for columns to be able to have bidirectional referencing
- [x] add functionality for the new data
- [x] add tests

**Comment by lyubageorgieva** [comment]
Turn into a US because it is not a BUG

**Comment by lyubageorgieva** [comment]
@MaximeJoanisse Will turn it into a US

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/fb7066b5-ec42-479f-8e5a-315eb88b19fa

this includes sign-off for #212

**Comment by TheOrangeDuke** [comment]
Looks good! 
Signing off!
