### ISSUE TITLE
[US] Automate publishing of PostGOAT image to Dockerhub

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#237]
As a platform developer, I want the image of the front-end application (PostGOAT) to be built and published to Dockerhub with every merge to main so that application users have access to the most up to date version of the application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must|             Medium          |              3      |

## Acceptance Criteria
Have a GitHub Actions workflow that :
- Runs on every merge to the main branch
- Builds the docker image from the front-end
- Publishes it to Dockerhub

## Risks
- Deploying the front-end to the public 

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
 - Stakeholder agreed to use GitHub Actions instead of DockerHub for an automated build
- [x] Complete the requirements of this US

## Tasks
- [x] Do some research to gather information on how to:
    - Build a docker image from GitHub Actions
    - Publish that same image to Dockerhub
    - Making sure that it is the same image that gets updated on Dockerhub
- [x] Implement the GitHub Actions workflow
- [x] Include automated, pre-publishing testing so that the new image gets tested before it is re-updated on dockerhub officially
- [x] Test it to make sure that it works as intended, both on the CI/CD side and the Dockerhub side

## Dependencies
This story depends on #206 as it will use the knowledge gathered from that story and incorporate it in the CI/CD.

**Comment by Alexicazana** [comment]
Trying to fix build fail; had to look into node16 deprecated issue and try to switch to node20 ([reading docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions))

<img width="1094" alt="Screenshot 2024-02-09 at 3 23 38 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/aea456db-2750-4fcb-87b1-c96298e0ce87">

**Comment by Alexicazana** [comment]
Working on fixing this

<img width="1440" alt="Screenshot 2024-02-09 at 4 02 21 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/0fab5e43-3f4d-4d6c-8440-e5e493ad8e1b">

**Comment by MariaR001** [comment]
Issue above is fixed!
https://github.com/WillTrem/UInnovate/assets/78176331/08e4579a-7759-4c21-a7ec-f992b9b33a19

**Comment by TheOrangeDuke** [comment]
Looks great! Signing off!
