### ISSUE TITLE
[US] (i18n) Show RAW Names

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#238]
As an application user, I want to display throughout the application the RAW i18n default translations, so that I can utilize the internationalization system.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |     Medium                 |         5           |

## Acceptance Criteria
- Displaying the RAW db names throughout the application via the default language, as per Stakeholder Requirements.

## Risks
- Not displaying all the raw db names, if the user hasn't filled the default language

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Default language column, that always remains on the Internalization tab.
- [ ] Dropdown default language selector, for the user to choose the default language to be used for the application.
- [ ] User being able to add a translation for each label, and being able to modify it. Changes reflected to the database.
- [ ] Raw names being reflected on the application

**Comment by lyubageorgieva** [comment]
## UI Mockup
<img width="909" alt="Screenshot 2024-02-05 at 10 13 20 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/28607d02-8795-426a-ae34-2f374ce2ba42">

**Comment by lyubageorgieva** [comment]
## Use Case Diagram
<img width="1009" alt="Screenshot 2024-02-05 at 10 32 48 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/4b96998c-efc2-41e9-b832-b6394edb5119">

**Comment by lyubageorgieva** [comment]
Before starting this US #280 would need to be completed to test the full functionality, hence it will be moved to next iteration
