### ISSUE TITLE
[US] Refresh Schema and Data

### ISSUE THREAD

**Issue by tsitirides** [WillTrem/UInnovate#24]
As an application developer, I want to have the ability to refresh the schema and the data by using the files and the script, so that I can easily update and synchronize the database schema and data with the latest definitions and datasets.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have | Medium | 4 |

## Acceptance Criteria
- Develop a script that takes the schema and data files as input.
- Include validation checks in the script to ensure the integrity of the data and schema.
- Add logging to record the details of the refresh process. 
## Risks
- Poor validation or error handling in the script may result in data loss or corruption during the refresh process.
- Data integrity issues if the refresh process does not handle insertions,  updates, or deletions correctly.
## Tasks
- [x] Task create a script that deletes everything in the database (DROPs the appdata tables)
- [x] Task create a script that creates new tables
- [x] Task create a script that inserts new data

**Comment by tsitirides** [comment]
# Demo Video

https://github.com/WillTrem/UInnovate/assets/47327032/6f5f6c41-b6df-4ae8-96f3-568da8b82f07

**Comment by tsitirides** [comment]
## Demo Steps

1. Open a terminal
2. Change directories to the UInnovate folder where the refresh_database.sh is located
3. From a terminal, run:
>:bulb: .\refresh_database.sh
4. A log file will be generated to see everything that was done to the DB and any errors that occurred

**Comment by tsitirides** [comment]
## Architecture Diagram

![ArchitectureSOEN490- US#24  Refresh Schema and Data drawio](https://github.com/WillTrem/UInnovate/assets/47327032/961b854e-7905-403b-b363-f1c273f66b9d)

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
