### ISSUE TITLE
[US] SOEN491 KPI Dashboard

### ISSUE THREAD

**Issue by MariaR001** [WillTrem/UInnovate#264]
The KPI dashboard is not part of our current project because it serves a distinct purpose from the main scope of our SOEN490 project (PostGOAT). It's being treated as an extra coding assignment/add on tool because it has separate requirements and functionality. The KPI dashboard's goal is to provide real-time visibility into important metrics and performance which allows users to monitor progress towards strategic objectives and identify areas that require attention or improvement.

As a user, I want to have a dashboard that can be easily customized so that I can display various information.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
|Could|            High          |          13          |

## Acceptance Criteria
- The dashboard allows users to easily customize the layout and content of tiles.
- Users can drag and drop tiles to rearrange them on the dashboard.
- Each tile can display various types of information, including numbers and graphs.
- Users can configure the dashboard layout and content, and the configuration is stored in an object.
- Changes made to the dashboard configuration persist between sessions.
- The dashboard is responsive and displays correctly on different screen sizes.
- Documentation is provided on how to use and customize the dashboard as well as how it will be implemented with our current tool PostGOAT

## Risks
- Technical Complexity: Implementing a dynamic and customizable dashboard may involve complex frontend development and state management.
- Performance: The dashboard's responsiveness and performance may degrade with a large number of tiles or complex configurations.

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Set up
- [ ] Make an easily editable tile-based frontend
- [ ] Make numbers and graphs  display on every tile
- [ ] Dashboard configuration is able to be stored in an object
- [ ] Publish the frontend library as a react component

Link to other repo: [491-KPI-DASHBOARD](https://github.com/MariaR001/KPI-DASHBOARD)
