### ISSUE TITLE
[US] List View - Column-based filtering

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#267]
As an application user, I want to be able to filter the columns of the tables, so that I can customize the filter experience and obtain the desired data in a more efficient way.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low                      |         4           |

## Acceptance Criteria
- Ability to filter a desired column to obtain desired data
- Has to go through the VMD

## Risks
- Adding Complexity to the VMD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] UI Mockup
- [x] Research about the columns to have filtering
- [x] Add filtering UI to tables
- [x] Add filtering to make the API call properly

## Visual Example from [Element Plus](https://element-plus.org/en-US/component/table.html#sorting)
<img width="829" alt="Screenshot 2024-02-14 at 9 54 05 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/ca0bd2a7-0072-493e-b096-ec8eacbfc721">

<img width="748" alt="Screenshot 2024-02-14 at 9 54 56 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/fc3d6073-6d14-476d-8a9b-5e419265d7af">

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/d2c3cc15-4b75-4834-9e57-01aaf4d7c0e2

**Comment by TheOrangeDuke** [comment]
looks good!
Signing off!
