### ISSUE TITLE
[US] In-List Column Value Editing

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#268]
As an application user, I want to have column value editing, so that when displaying a list for a specific table, on double-click, to switch the display mode to a value-editing display, enabling editing and on single click to open the details-view panel. (This behaviour would be close to the edit mode in Excel)

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |        Medium              |      5              |

## Acceptance Criteria
- Ability to column edit values of specific tables on the List View

## Risks
- TBD

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Testing
- [x] Enable cell edit mode on double-click
- [x] Once a key is pressed or enter button clicked, save the new value to replacing the previous
- [x] Changes need to be reflected on the front-end and database
- [x] Pop-up confirming if the user wants to edit the cell, or pop-up telling the user they cannot edit a specific cell? Research about the best option.

**Comment by tsitirides** [comment]
https://github.com/WillTrem/UInnovate/assets/47327032/b5d5897c-7b90-46b6-8426-e372e0df10b1
