### ISSUE TITLE
[US] (i18n) Refresh Button

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#269]
As a application user, I want to have a ``Refresh`` button in the InternationalizationTab, so that can update the i18n_keys table.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       Low               |     3               |

## Acceptance Criteria
- On ``Refresh`` button clicked, the i18n_keys table should contain all the new changes and be refreshed

## Risks
- N\A

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] UI Mockup
- [ ] Testing
- [ ] Refresh Button
- [ ] Stored procedure to handle updating the i18n_keys table
- [ ] Refresh button functionality
