### ISSUE TITLE
[US] Settings Saving On Change

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#273]
As an application configurator, I want the settings I change to be directly saved into the database rather than from a batch, so that the database always stores the most up to date version.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could have |           Low           |             3       |

## Acceptance Criteria
- The settings of the application are now saved as the change occurs, rather than in a batch fashion through timer as is currently the case
- A toast menu (popup) shows up upon confirmation that the settings has been successfully saved in the database. 
- The toast menu should contain information about the configuration that was saved
## Risks
- Modification of already existing mechanism has the potential to break the current system
## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements

## Tasks
- [x] Modify the front-end's saving mechanism
- [x] Add a generic toast menu mechanism for the platform
- [x] Make the toast menu trigger on saving to the database

**Comment by WillTrem** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/64431699/7410a514-43c9-4db3-a7bd-bc6fe6b9fd45

**Comment by TheOrangeDuke** [comment]
Signing off!
