### ISSUE TITLE
[US] File Display

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#275]
As an application user, I want to have an attachment field that shows me the existing files, the amount of current files, and for it to be located below the columns from the table , so that I can easily manage files.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |       Low               |      3              |

## Acceptance Criteria
- Attachment field is located between the columns and the lookup tables
- Existing files are already displayed without having to click on a button
- Displays the current amount of files

## Risks
- TBD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] File/attachment field should be located under the columns before the Lookup Tables
- [x] Remove the "Show Files" button, if a file exists it should already be displayed 
- [x] When showing the "upload file" show "Currently 0 files"

**Comment by lyubageorgieva** [comment]
US was finished during iteration 11, however due to conflicts when merging it was only merged during iteration 12

**Comment by TheOrangeDuke** [comment]
Saw this during the hackathon, looks good! Signing off!
