### ISSUE TITLE
[US] Foreign-key Dropdown Selector and Display Fields

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#276]
As a application user, I want to set my foreign values with an easy to understand dropdown, so that I can configure my database quickly and easily.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |           High           |         8           |

## Acceptance Criteria
Whenever a table has a column that is a foreign key, we want it to display the display field value of the table row it is referencing. In addition, setting a foreign key value in the modal should be a dropdown, with a list of the display fields of each row of the referenced table.

## Risks
Mapping foreign keys to their display field values will be tricky, it may take some time to find the correct combination of API calls + VMD accessing

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Implement the functionality to map the value of a foreign key in a table to its corressponding display field in the referenced table
- [ ] Have the foreign key columns of tables display the display field value of the referenced table by default
- [ ] Develop a function to make an fetch all the display field values of a refereneced table, along with the primary keys, based on a foreign key column in the original table
- [ ] Create a dropdown that displays when editing or adding foreign-key columns, that lists all the display field values of the referenced table (selecting a display field value should set the foreign key to its correct value)

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/25f83046-2216-4c3a-bd9e-b6490be1d33f
