### ISSUE TITLE
[US] Refactoring of the Environmental Variables Display

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#277]
As an application developer, I want the design of the `Environment Variables` display to be consistent with the other existing tabs, so that the same design is maintained throughout the application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |     Low                 |         4           |

## Acceptance Criteria
- Proper colours of buttons
- Environment variables in a table
- Ability to edit the environment variables via the table
- Improve the readability for users
- Having a UI friendly tab that remains consistent with the other tabs

## Risks
- None

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Fix the alignment and colours of the buttons in the modal
- [ ] Add the environment variables into a table (See InternationalizationTab as an example)
- [ ] Fix the editing mode, to be more UI friendly (See InternationalizationTab as an example)
- [ ] Fix the readability, such to remove the repeated `Environment Variable(s)` 3 times
<img width="267" alt="Screenshot 2024-02-16 at 4 00 12 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/bb29307d-8421-4ed9-b381-6c11450cfcbb">

**Comment by lyubageorgieva** [comment]
## UI Mockup 
<img width="913" alt="Screenshot 2024-03-26 at 10 37 21 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/3759710d-381d-43a2-923e-a339df8ed077">
