### ISSUE TITLE
[US] (i18n) Adding Languages/ Default Languages as Dropdowns

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#278]
As an application developer, I want the users to add new languages for i18n via a dropdown, so that the user experience is improved and the user doesn't need to manually input the language names and codes.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |    Low                  |        5           |

## Acceptance Criteria
- Keep the same functionality to add a language as previously
- Ability to add a new language via a dropdown
- Once the language is selected, automatically associate the language code
-  Ability to add a default language to be displayed in the i18n tab via a dropdown
- Once a default language is selected to show only the labels from the view associated with that language_code

## Risks
- N/A

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] UI mockup
- [x] In the `Add Language Modal`, have a dropdown for the languages.
- [x] The dropdown should contain a list of languages (research for an external tool)
- [x] Once a language is selected, the language should be automatically associated to the language code `ISO 639-1`
- [x] Adding the default language dropdown
- [x] Setting up 'English' as the default language
- [x] Once a language is selected to be a default language, the changes need to be reflected on the UI, hence in the column as LANG:<language_code>
- [x] The selected default language should also display the proper values for the labels from the view corresponding to the language

## Note
Check this package to implement the feature
https://www.npmjs.com/package/iso-639-1

**Comment by lyubageorgieva** [comment]
## UI mockup
<img width="834" alt="Screenshot 2024-02-18 at 9 47 02 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/5c28098a-ed0a-430e-802b-cb04b7bb0065">

**Comment by lyubageorgieva** [comment]
## Use Case Diagram
<img width="689" alt="Screenshot 2024-02-18 at 9 58 06 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/8c2993b4-ead0-4c67-81f5-8e4c801282a6">

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/379c2943-2a08-4c2e-b950-e347d395e8af

**Comment by lyubageorgieva** [comment]
## Additional notes

In the video, it's mentioned that default languages wasn't yet implemented but afterwards I added another commit to the existing PR to fix it. And it works as depicted in the following screenshot

<img width="1176" alt="Screenshot 2024-02-19 at 11 32 41 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/85fa2b16-65c6-4e82-9dde-faf4224c2447">
