### ISSUE TITLE
[US] (i18n) Adding Translations to Labels

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#280]
As a an application user, I want to add translations to the existing labels, so that I can utilize i18n by displaying the translations instead of the raw database names.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Medium                     |          5        |

## Acceptance Criteria
- Ability to add a translation to existing labels (reflected on UI and database)
- Ability to edit the translation (reflected on UI and database)

## Risks
- TBD

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] UI mockup
- [x] Use Case Diagram
- [x] Adding a default language `English`
- [x] Enabling the cells to add, and edit translations
- [x] Testing

**Comment by lyubageorgieva** [comment]
## Use Case Diagram
<img width="726" alt="Screenshot 2024-03-23 at 12 38 42 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/2192f71f-3499-4bed-85cf-6c0e3ef805b0">

**Comment by lyubageorgieva** [comment]
## UI mockup
<img width="999" alt="Screenshot 2024-03-23 at 12 39 12 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/c18322bc-981c-4c47-84b4-1e3247514ae3">

**Comment by lyubageorgieva** [comment]
## Testing Coverage Added for i18n
#262 
![image](https://github.com/WillTrem/UInnovate/assets/74876532/5fce64e1-cc13-44d0-ae19-a5e3d8ff5e48)
<img width="724" alt="Screenshot 2024-03-23 at 12 42 52 AM" src="https://github.com/WillTrem/UInnovate/assets/74876532/9a954d90-5dcd-4848-94d2-d9d527be1421">

There will be more tests added!

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/c301da4a-b10d-4aaa-8ba4-05a81f7ad6a7

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
