### ISSUE TITLE
[US] Correct In-list editing per column value type

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#281]
As an application user, I want to edit values on double click with the correct form type, so that editing rows of my table is easy.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |           Low           |           5         |

## Acceptance Criteria
When a value is double clicked to edit it, it displays the correct type of form depending on the value type of the column as a whole. Here is the list of options:
- foreign key : dropdown which lists display fields, overrides other options, see #276 
- text : regular text field
- boolean : true/false toggle
- integer, double and money : number selector
(if there are cases missing from here, please ask the Stakeholder for their opinion first)

## Risks
Possible issues related to double-clicking functionality having been done correctly, as well as grabbing the column type properly

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US
- [x] Must have #268 completed before starting this story

## Tasks
- [x] Fetch the column type when double clicking on a value in a table
- [x] Design each of the input fields mentioned in accpetance criteria
- [x] Develop a function to display the correct input field based on the column of the double-clicked value (ensure values are also still updated properly in the DB on save)
