### ISSUE TITLE
[US] Bind additional view navigation to the main tab pane to visualize the data

### ISSUE THREAD

**Issue by witnick** [WillTrem/UInnovate#303]
As a user, I want to navigate my main view between the additional view available, so that [ I can accomplish Z ].

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |     Low                 |         3           |

## Acceptance Criteria
Given a table has more than a default view, clicking on other views should update the tab pane with the selected view

## Pre-requisites
N/A

## Tasks
- [ ] Refactor Additional View navigation bar to update the selected view type
- [ ] Show the selected view type in the tab pane (section in red box)
- [ ] Make selected view type be the default on first load 
- [ ] Make the navigation properties persistent so the user doesn't have to reselect the view type  when navigating away and coming back(user experience)

Extra details:
![image](https://github.com/WillTrem/UInnovate/assets/10947924/687fafda-78a8-4d90-bfa3-4bdbe4ee61a6)

**Comment by witnick** [comment]
![adddition_views_pane_navigation](https://github.com/WillTrem/UInnovate/assets/10947924/d31c71ad-753c-4d10-89d7-70e7dfb25ad2)

**Comment by TheOrangeDuke** [comment]
Signing off!
