### ISSUE TITLE
[US] Adding a delete button for rows in TableListView

### ISSUE THREAD

**Issue by MaximeJoanisse** [WillTrem/UInnovate#309]
As a user, I want to be able to delete a row, so that I can clean my data up.

| MoSCoW      |  Risk               | Story Points  |
| ------------ |------------- | ------------- |
| Must|          low            |          4          |

## Acceptance Criteria
seeing garbage icons next to each row, which once pressed will delete the row 
## Risks
adding complexity to table list view
## Pre-requisites
- [x] Meet with the stakeholders to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] add the button to the row
- [x] add functionality 
- [x] test for button

**Comment by MaximeJoanisse** [comment]
Rough Design 
![image](https://github.com/WillTrem/UInnovate/assets/92006009/07313cec-ccab-49cb-90e3-d70904b711be)

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/63a41a80-5e71-4eb5-bf3a-aa1efffc61d8

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
