### ISSUE TITLE
[US] Virtual Model Definition

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#31]
As an application user, I want to have a virtual model definition, so that I can dynamically have access to my tables and columns when trying to use my database

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must-have | Low | 2 SP |

## Acceptance Criteria
- The virtual model successfully displays the tables and columns of the database.
## Risks
- The VMD displays the wrong information to the application user
- The REST API does not function as intended, and the VMD can't display the tables
## Tasks
- [x] Setup the PostgREST API container
- [x] Make React components in the frontend to act as the VMD
- [x] Make API calls in the VMD directory to fetch the table and column information
- [x]  Arrange the information in a specific data structure (Array for tables, maybe JSON object for tables + columns)

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/4eefceec-7301-4601-ae3b-66b2f34a237c

**Comment by TheOrangeDuke** [comment]
This looks good. Signing this story off.
