### ISSUE TITLE
Modify additional view navbar to access view directly by name

### ISSUE THREAD

**Issue by witnick** [WillTrem/UInnovate#321]
As a user with access to a table with multiple custom views, I want to be able to show the views by name in the view navbar.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must            |   low    |                  3 |

## Acceptance Criteria
Need to be able to view the different additional views in the view bar by name if multiple views are available 

## Risks
Risk: Unauthorized access to custom views.
Mitigation: Apply proper authorization mechanisms to ensure that only authorized users can access and modify custom views.

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements

## Tasks
- [x] Make the additional views always visible if additional views are available
- [x] Change view type in the navigation to the view name
- [x] Link directly to the view without having to navigate to the table 
- [x] Make the view take the whole view space and hide the table tab navigation when in the additional view

**Comment by witnick** [comment]
![customView_data_navigation](https://github.com/WillTrem/UInnovate/assets/10947924/c76c3b67-21f8-4c2b-a506-8e14aebebf8e)

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/b6fa0910-8dd2-4bb6-91ac-d809fabc0813
