### ISSUE TITLE
[US] Update Mkdocs and README

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#328]
As an application user, I want to have all the necessary information on the mkdocs and mkdocs, so that know everything there is about my application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |      Low                |         5           |

## Acceptance Criteria
- Having a complete documentation ready for stakeholder hand-off

## Risks
- No risk

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Add sections for each pertinent part of the README on the mkdocs
-  Add a section about "Here's how you set up the app"
- Add a section information about the VMD "Here's how the VMD works"
- Add a section about how "export/imports" work
- etc...
- [ ] Simultaneously, also update the README with the newest updates such as we aren't using cypress anymore

**Comment by GuardiansAscend** [comment]
https://github.com/WillTrem/UInnovate/assets/61199167/1360ebf6-afec-45e8-8122-bf12a07fcd31
