### ISSUE TITLE
[US] UI Refactoring for Consistency

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#329]
As a user, I want to have a UI friendly application, so that I can have a consistent application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |        Low              |         3           |

## Acceptance Criteria
- Have consistency with the UI throughout the application

## Risks
- No Risk 

## Pre-requisites
- [ ] Meet with the stakeholder to clarify the requirements
- [ ] Complete the requirements of this US

## Tasks
- [ ] Make the UI more consistent
- [ ] Fix the 2000's buttons for "Adding a lookup tables"
<img width="689" alt="Screenshot 2024-03-24 at 12 48 57 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/4388d041-e648-4869-b0ed-8536f3345229">

Change it to this button
- Maybe make the button smaller, more square so it fits better in the page
<img width="95" alt="Screenshot 2024-03-24 at 12 58 04 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/15c553b8-9175-4ece-9805-b829ab3f63ac">

- [ ] Verify all the modals, and make them consistent.
- [ ] Make all modal titles Pascal Case for example "Add New Language" capitalize each new word!
- [ ] Save button having the secondary color "Blue" and only being named "Save" not "Save Changes"
- [ ] Same gap between twin buttons in each modal
- [ ] Add button only being named "Add"
- [ ] Change the "Add Enum Row", "Add List Row", and "Add New User" to a different type of modal. The type of modal depicted at the end, with the line after the title etc,. For more information ask @lyubageorgieva.

<img width="563" alt="Screenshot 2024-03-24 at 12 50 04 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/ffe30426-3c47-49d9-92a5-7ecf77bcdecd">
<img width="509" alt="Screenshot 2024-03-24 at 12 51 58 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/ea8afa96-355d-4bf1-a28a-0b68abcf2d0a">
<img width="563" alt="Screenshot 2024-03-24 at 1 11 16 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/2a0dfed2-ca83-47e9-8256-bd65ec2e0d41">

- This look of modal should be the targeted feel, but needs the title to be Pascal Case and the "Save Changes" button to be just "Save".
<img width="601" alt="Screenshot 2024-03-24 at 12 53 50 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/924c19d3-6366-4335-a046-1763761c679b">

- [ ] Verify all these other modals
<img width="654" alt="Screenshot 2024-03-24 at 12 52 57 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/ace15775-0967-4882-bb64-7964b7a0e326">

<img width="712" alt="Screenshot 2024-03-24 at 12 53 11 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/cb3abf3a-4278-4ce7-b352-f2e5a0f918ed">

<img width="601" alt="Screenshot 2024-03-24 at 12 53 50 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/924c19d3-6366-4335-a046-1763761c679b">

<img width="589" alt="Screenshot 2024-03-24 at 12 56 01 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/a3d37379-17ff-485d-8ef7-75e713ef7e4b">

<img width="596" alt="Screenshot 2024-03-24 at 12 55 29 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/ca526f36-f01b-4e5e-9c41-ccbe8adef5b7">

- Feel free to fix any other inconsistency you find! maybe some aren't discovered yet..

**Comment by TheOrangeDuke** [comment]
Looks good to me! Signing off!
