### ISSUE TITLE
[US] Home Page Redeisgn

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#362]
| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |          Low            |            2        |

## Acceptance Criteria
Redesign of the Home page for the kiosk. This is a retroactive User story, we didnt originally have a story attributed to work done for the home page. The work was done in #355.

## Risks
None

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Redesign home page for the demo kiosk day
- [x] Make sure it is responsive, and changes its text depending on login
