### ISSUE TITLE
[US] Custom Calendar View

### ISSUE THREAD

**Issue by Alexicazana** [WillTrem/UInnovate#363]
As a user, I want to view the unit scheduler as a calendar view, so that I can have an overview of all available items by date.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could |           Medium           |        5            |

## Acceptance Criteria
- Able to display a calendar view of years and months
- Able to see the status of items

## Risks
- Modification to existing db schema and tables

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Calendar implementation
- [x] Create custom view for adding new tools and availability
- [x] Ensure calendar correctly displays tools and their availability period

**Comment by Alexicazana** [comment]
## Calendar created and implemented inside unit scheduler (Tools use case); accessible from home tab

<img width="1390" alt="Screenshot 2024-06-18 at 12 10 03 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/3b417fbb-04f5-4f42-a11e-4d2b32a0f7b6">

**Comment by Alexicazana** [comment]
Issue found in displaying item status; correct database tables are fetched but unable to render status. Working on fix

<img width="1382" alt="Screenshot 2024-06-18 at 12 51 31 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/c8b2e2fd-5123-47bf-ac0b-ac5398972c61">

**Comment by Alexicazana** [comment]
Fetched relevant tables and rows; working on display and avail status

<img width="1440" alt="Screenshot 2024-06-18 at 1 00 24 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/d077d92e-c4b3-4296-b8d9-82fb5dd1592e">

**Comment by Alexicazana** [comment]
Due to a discrepancy in some of the already existing tables, I created a new table with sample data of available tools for rental. This is created using already existing tables.

<img width="1127" alt="Screenshot 2024-06-18 at 1 34 59 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/85096513-d6e3-456a-add0-fb2a94f8eac9">

**Comment by Alexicazana** [comment]
Correctly cross referencing tool table and available_tools using tool_id

<img width="1440" alt="Screenshot 2024-06-18 at 2 51 49 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/d7d65f10-1adc-41a7-99a9-b147ef5edc37">

**Comment by Alexicazana** [comment]
Fixed undefined tool name and display!

<img width="1387" alt="Screenshot 2024-06-18 at 2 57 06 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/6eccfe2a-6bf9-4b86-807c-90eb8a927b5d">

**Comment by Alexicazana** [comment]
Created a new view inside the default app_rentals homepage view in order to display the available tools separately.

<img width="1382" alt="Screenshot 2024-06-18 at 2 57 56 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/d61e09a0-18c6-4276-85b2-d13b0157152c">

**Comment by Alexicazana** [comment]
Added ability to add new tools for availability.

<img width="541" alt="Screenshot 2024-06-18 at 2 58 55 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/06f448ae-50e1-4f29-9812-e11489049f9f">

**Comment by Alexicazana** [comment]
Brief architecture diagram for this calendar view (forgot to attach earlier).

Show interactions between database and new calendar view via the VMD, a new table created in the database, and UI mockups.
<img width="1271" alt="Screenshot 2024-06-18 at 5 24 00 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/40d48e46-f94c-4e28-a555-8598c1d521b0">

**Comment by Alexicazana** [comment]
Done, awaiting stakeholder review

DEMO:
https://github.com/WillTrem/UInnovate/assets/55753055/8299315a-537f-45f0-8b8b-dfce68f3b525


** No PR linked, since cannot do that alone without review, but development branch linked to the issue.

**Comment by TheOrangeDuke** [comment]
Looks good to me! signing off.

**Comment by Alexicazana** [comment]
Interaction Diagram for calendar view

<img width="929" alt="Screenshot 2024-07-09 at 10 46 00 AM" src="https://github.com/WillTrem/UInnovate/assets/55753055/3871af6e-4c13-47de-8142-0fb8c2838d21">

**Comment by Alexicazana** [comment]
NEW DEMO video (includes a run through of the code at the end):

https://github.com/WillTrem/UInnovate/assets/55753055/14e204fb-f2b1-420c-835b-95897faad148
