### ISSUE TITLE
[US] Unit Scheduler Calendar View

### ISSUE THREAD

**Issue by Alexicazana** [WillTrem/UInnovate#364]
As a application user, I want to have a timeline view of the future calibration units request, so that can know when tools will need to be calibrated.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should   |         Medium             |    5                |

## Acceptance Criteria
- Properly displays tools that are scheduled to be calibrated in a calendar

## Risks
- Being able to fetch the correct data from the database given structure of tables 

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements

## Tasks
- [x] Create unit scheduler items to be displayed
- [x] Create calendar view to display items

**Comment by Alexicazana** [comment]
Unit Scheduler UI mockups + software architecture diagram for accessing database

<img width="976" alt="Screenshot 2024-06-18 at 5 44 44 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/c20603bb-b1eb-4394-bdba-2d17c167d06b">

**Comment by Alexicazana** [comment]
Done, awaiting stakeholder approval.

DEMO:
https://github.com/WillTrem/UInnovate/assets/55753055/81cf72fe-7e68-4a0c-a9f6-93cca356a3ba

**Development branch is linked to this issue.

**Comment by TheOrangeDuke** [comment]
Looks good to me! Signing off!

**Comment by Alexicazana** [comment]
<img width="929" alt="Screenshot 2024-07-09 at 10 46 00 AM" src="https://github.com/WillTrem/UInnovate/assets/55753055/f7a50bf6-1183-490f-ac1c-72fb4e6f596b">

**Comment by Alexicazana** [comment]
NEW DEMO video for 364 including a code walkthrough:
https://github.com/WillTrem/UInnovate/assets/55753055/73753a84-bbca-4170-a4eb-b30e7bc08ce9
