### ISSUE TITLE
[US] Search Page with Search Functionality

### ISSUE THREAD

**Issue by Alexicazana** [WillTrem/UInnovate#365]
As a an application user, I want to have access to a search page, so that I can query and search for specific rows from all available tables and column names and get a search result.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |  Medium                    |       7             |

## Acceptance Criteria
- Search page accessible through nav bar for USER role
- User can successfully select the table they want to search (from a list of all available tables in the database)
- User can successfully select which column they want to search
- User can enter the value of the column they're looking for
- User can either see the result of their query displayed, or sees an error message indicating the row was not found

## Risks
- Being able to fetch and display all tables and columns of those tables in a meaningful way for the user
- Allowing application user role to access this page though it sits at the same level as Settings page (which is NOT accessible to user role)
- Ensuring query results are correct and complete information for the user (validation required)

## Pre-requisites
- [x] VMD is appropriately accessible
- [x] Roles are well defined for this new page

## Tasks
- [ ] Create separate search page accessible from NavBar
- [ ] Allow app user roles to access this
- [ ] Create search functionality
- [ ] Create search output
- [ ] Ensure UI is consistent
- [ ] Add testing to make sure the displayed information from the search results is accurate and complete!

**Comment by Alexicazana** [comment]
Initial UI mockups for Search Page:

<img width="833" alt="Screenshot 2024-06-27 at 2 06 15 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/dacc7e2c-cad3-48bf-9b00-132d51fc3efc">

**Comment by Alexicazana** [comment]
Search handles value in input field appropriately; for column 'tool_description', the rows outputted are all those that contain the value in the input field; no need for exact match since description is lengthy, and user may not know exact description.

<img width="811" alt="Screenshot 2024-06-27 at 2 25 12 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/bfa0bb40-50e5-4ea5-baef-a8d353c35782">

<img width="1440" alt="Screenshot 2024-06-27 at 1 44 07 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/1e3dc264-f70a-4819-b29f-6a97e9a43579">

**Comment by Alexicazana** [comment]
Search handles value in input field appropriately; for column 'tool_description', the rows outputted are all those that contain the value in the input field; no need for exact match since description is lengthy, and user may not know exact description.

<img width="813" alt="Screenshot 2024-06-27 at 2 28 20 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/231e9de3-94a3-4584-a093-80625f262347">


<img width="1203" alt="Screenshot 2024-06-27 at 2 27 59 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/fba07de1-a476-4771-a67b-160fa9079615">

**Comment by Alexicazana** [comment]
Added some styling to be consistent with the rest of the components:


<img width="1439" alt="Screenshot 2024-06-27 at 3 08 45 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/a0a9f501-fc97-47f0-a71c-10e31623a5fc">

**Comment by Alexicazana** [comment]
(Forgot to include)

Interaction diagram between User, Search page, VMD


<img width="1082" alt="Screenshot 2024-06-27 at 3 44 46 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/77557087-7f56-40cd-8487-ae858c59d47f">

**Comment by Alexicazana** [comment]
DEMO:
https://github.com/WillTrem/UInnovate/assets/55753055/9c2cea43-6e3a-450a-83ec-b17a9c4104d3
