### ISSUE TITLE
[US] Set up PostgREST Endpoint Testing Using Postman

### ISSUE THREAD

**Issue by Alexicazana** [WillTrem/UInnovate#38]
As a developer, I want to test PostgREST endpoints using Postman to ensure the system's reliability and correctness.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
|      Should      |    Medium      |            5          |

## Acceptance Criteria

- All publicly exposed PostgREST endpoints have corresponding tests in Postman.
- Responses are checked for correct data structure and data values.
- Tests validate successful response scenarios (e.g., a 200 OK for a successful GET request).
- Tests validate error scenarios (e.g., 404 Not Found for a non-existent resource or 400 Bad Request for invalid input).
- Pass criteria: All Postman tests run successfully without errors and any expected failures (e.g., deliberately testing an error scenario) should be documented and produce the expected error response.

## Risks
- Deeper understanding of PostgREST and of how Postman works is needed.
- Task relatedness to US #21 which may require additional team members collaboration

## Tasks
- [x] Install and setup Postman
- [x] Create new collection for tests to group and manage
- [x] Write tests in Postman to verify the behavior of the endpoint
- [x] Confirm wether or not parametrized testing integration is needed for testing the same endpoint with different data (requires confirmation)

**Comment by Alexicazana** [comment]
Created Postman Collection with some tests for what we have so far in our db (see below). Integrated the collection into GitHub repo using Postman.
<img width="1440" alt="Screenshot 2023-10-27 at 6 16 09 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/e2ff50aa-1864-476e-b83e-0ed09d9b4135">

**Comment by Alexicazana** [comment]
Here is an example of some of the tests written:
<img width="1440" alt="Screenshot 2023-10-27 at 6 17 37 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/014ccda1-b96c-4899-8866-5f007f07c29e">

**Comment by Alexicazana** [comment]
Note: There's a three person limit on how many people can be in a Postman Collection, so we will have to evaluate wether or not we can move forward with this approach in the future.

**Comment by Alexicazana** [comment]
https://github.com/WillTrem/UInnovate/assets/55753055/8a0a0b8e-d0ef-4ead-99cb-1d58f38ab40c

**Comment by TheOrangeDuke** [comment]
Looks good, signing off!
