### ISSUE TITLE
[US] Create Database for Use Case

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#4]
As a platform developer, I want to have a local “dummy” database representing a simple use case, so that I can have data to use for building and testing the rest of the platform.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
|  Must have |   Medium        | 2                   |

## Tasks
- [x] Create a postgres instance in docker image for the database
- [x] Create the database and import the data
- [x] Create a database dump so that everyone has access to the same data

**Comment by lyubageorgieva** [comment]
## Architecture Diagram 
![image](https://github.com/WillTrem/UInnovate/assets/74876532/1132a99a-242e-4aae-ae5a-f1207a103082)

**Comment by WillTrem** [comment]
## Demo Video
With the collaboration of @lyubageorgieva  and @WillTrem 


https://github.com/WillTrem/UInnovate/assets/64431699/db289a9c-59cf-49aa-bfce-b6503880eac8

**Comment by TheOrangeDuke** [comment]
This looks good. Signing this story off.
