### ISSUE TITLE
[US] Application config tables

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#40]
As an application developer, I want the configuration of the application I’m developing to be persisted so that it may be applied on subsequent use of the application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |  Low                    | 3 SP                    |

## Acceptance Criteria
- 2 new database tables are created in the `meta` schema:
    - Table `appconfig_properties` catalogs any properties that are able to be modified
    - Table `appconfig_values` contains the values set for the different properties on the different components of the application
    > Note that a given property could be applied to multiple components, such as different columns/tables. Therefore, in the `appconfig_values` table, a given property could be present more than once. This can't happen in the `appconfig_properties` table.
- Tables are automatically created at the boot of the database
- `appconfig_properties` table may be populated with some properties
- Both tables are accessible via postgREST
- Configuration versioning is **out of the scope of this story**

## Risks
- Added database complexity
- Some properties might not be useful
- Some properties might be missed

## Tasks
- [x] Design the two app config tables
- [x] Write SQL statements to create the schema + the two tables
- [x] Add the schema to docker compose file for postgREST
- [x] Design some properties
- [x] Add properties to the `properties` table

**Comment by WillTrem** [comment]
## ER Diagram
This is the initial design for the two new tables brought by this story. 
It may very well be subject to modifications.
![image](https://github.com/WillTrem/UInnovate/assets/64431699/cb6425f1-6e3f-4aa7-a147-66e70f640b62)

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!

**Comment by adivardhan1000** [comment]
@WillTrem 
Everything look good. 
I might have missed something but one of the story goals is "Both tables are accessible via postgREST" but I don't see that in the demo. Is the rest API working and the data getting fetched correctly?

**Comment by WillTrem** [comment]
> @WillTrem 
> Everything look good. 
> I might have missed something but one of the story goals is "Both tables are accessible via postgREST" but I don't see that in the demo. Is the rest API working and the data getting fetched correctly?

@adivardhan1000
Yes, this has been implemented and it's fully working! I didn't show it because I didn't add anything special to the code for it to work (the API is generated automatically from PostgREST). However I agree that it should be shown nonetheles, I'll keep this in mind for future demos :)

**Comment by adivardhan1000** [comment]
Sounds good, I just wanted to make sure if it works.
