### ISSUE TITLE
[US] Create Data Flow Diagram

### ISSUE THREAD

**Issue by AfandiM** [WillTrem/UInnovate#53]
As a platform developer, I want to be able to consult an agreed upon standard for how the system's data will flow between the various entities, so that I can better understand the system and the tasks assigned to me.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
|   Should  |    Low                  |  2                 |

## Acceptance Criteria
- Have a set, agreed upon, diagram that accurately represents the flow of data in the system
## Risks
- Inaccurate diagram which might cause more confusion in future tasks and user stories
## Tasks
- [x] Define the different entities in the system
- [x] Define the data interchanged
- [x] Connect every component together

**Comment by AfandiM** [comment]
I updated the overall architecture diagram to better fit the vision we have for the UInnovate App: added some of the main files that are used in the app, as well as more detailed connections between the major components.

![image](https://github.com/WillTrem/UInnovate/assets/84986555/64de122a-8f8e-4a53-86f9-971741afa83b)

Additionally, I decided to draw a data flow diagram rather than a class diagram to represent the system: by design, the UInnovate application lacks the concept of a "class", and is rather focused on the flow of data between semi-dependent entities.

![image](https://github.com/WillTrem/UInnovate/assets/84986555/cdeef176-83ce-44ba-a984-4b6b5232bf6d)

**Comment by Alexicazana** [comment]
Awesome work

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
