### ISSUE TITLE
[US] Adding Details View 

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#60]
As an application user, I want to click on a row in the table so that a side panel opens that will show all of the row's data.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |     Medium      |         5        |

## Acceptance Criteria
- Ability to hide/unhide the side panel
- Ability to display a Details View of a certain row
- Ensuring that all existing attributes are presented on the side panel with the proper data from the database.

## Risks
- Adding complexity to the Virtual Model Definition

## Tasks
- [x] Adjust the ListView to have a hideable side panel
- [x] In the ListView table, on row click, open the side panel
- [x] When the side panel is open, show all the attributes 
- [x] For each attribute, populate with data from the database
- [x] Component testing using cypress

**Comment by lyubageorgieva** [comment]
## Figma Mockup
![image](https://github.com/WillTrem/UInnovate/assets/74876532/299443a4-9823-45b0-8fb6-cf349164ebed)

**Comment by lyubageorgieva** [comment]
## Demo Video

https://github.com/WillTrem/UInnovate/assets/74876532/314f2300-174e-4528-b57f-68911ed2024f

**Comment by TheOrangeDuke** [comment]
This looks great! Congratulations!
Signing off!
