### ISSUE TITLE
[US] Update Use Case #1

### ISSUE THREAD

**Issue by AfandiM** [WillTrem/UInnovate#62]
As a platform developer, I want to adjust the existing use case to meet new requirements established by the stakeholder, so that I can better illustrate potential needs that the user may have

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should | Low                      |  4                  |

## Acceptance Criteria
- The requirements expressed by the stakeholder must be respected and met.
## Risks
- Confusion about the requirements set by the stakeholder.
## Tasks
- [x] Adding properties for displayFields
- [x] Documenting the resulting API that is generated by postgREST, identifying the most common and useful queries needed
- [x] Documenting the use case from a requirements perspective, for future testing and verification
- [x] Update the ER Diagram of Use Case 1 and add it both to the API documentation and requirements documentation

## Note
**This user story is related to US #57, as we need to set up the MkDocs first, please coordinate with the other assignee.**

**Comment by GuardiansAscend** [comment]
![UInnovate Tool Rentals](https://github.com/WillTrem/UInnovate/assets/61199167/de64a9b6-a63b-417d-b7d6-392866596ca4)
ER diagram created for this user story:

**Comment by GuardiansAscend** [comment]
Requirements of the Use Case 1 documented here: https://docs.google.com/document/d/1PTHvqb4Duqy59Ho4XWXnXYZGBHXeDePRZtlC_EZXbsY/edit

**Comment by GuardiansAscend** [comment]
Demo:
https://github.com/WillTrem/UInnovate/assets/61199167/bba98802-eb07-4468-8084-f644e3abbfae

**Comment by TheOrangeDuke** [comment]
Looks great!
Signed off!
