### ISSUE TITLE
[US] Adding Component Display Type

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#63]
As an application configurator, I want to configure the "DisplayTypes" of columns, so that when they are displayed, specific components are used such as date, number, text & longtext, and boolean.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |   Medium    |      5       |

## Acceptance Criteria
- Ability to click a row from a specific table displayed in the "Settings" page under the "Display" tab.
- Ability to view the proper "Display Type" based on the configurations.

## Risks
- Complexity of tabularizing view configurations
- Complexity of loading view configurations onto VMD

## Tasks
- [x] UI Mockup Figma
- [x] Use Case Diagram or any other if needed?
- [x] Start with an initial list of 5 visual components such as date, number, text & longtext, and boolean from the UI library currently used (Bootstrap), or look into Material UI.
- [x] Add a dropdown item for each (in the settings pane)
- [x] Store the configuration of the display types
- [x] Retrieve the configuration of the display types to the VMD.
- [x] Testing 

## Note
**This US is dependent on the status of #19 because the front-end feature is displayed on the same page. Therefore, the front-end of the other US must be completed first, please coordinate with the other assignee.**

**Comment by AfandiM** [comment]
https://github.com/WillTrem/UInnovate/assets/84986555/96ab1c1c-a898-44b7-9aa4-fb07c183933f
