### ISSUE TITLE
[US] Milestone Document Release 1

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#64]
As a platform developer, I want to update the milestone document regarding the current UInnovate project, so any user can refer to the document to understand the current progress. 

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |          Low            |          3          |

## Acceptance Criteria
- Have a document with its majority sections completed for Iteration 4, which is Release 1 of UInnovate.

## Risks
- No Risks
## Tasks
- [ ] Update the Risks section by adding the most significant risk to the project. Elaborate on the risk, if it's a risk we have already attacked during Iterations 1, 2, or 3, you can elaborate on how it was attacked.
- [ ] Update Overall Arch and Class Diagram section with the most updated diagrams, describe any changes reflected to those diagrams.
- [ ] Infrastructures section to update and elaborate on the points of each infrastructure.
- [ ] Name Conventions section to polish, maybe add some of our current conventions in terms of US, PR's, folder namings, etc
- [ ] Code section to add 5 of the most important files up to date because they will be randomly checked for code quality. This could be changed during future releases.
- [ ] Testing and Continuous Integration section to link the 5 most important tests up to date. This could be changed during future releases. Describe the continuous integration environment.
- [ ] Double check the whole document, so it can be "release" ready for grading.

**Comment by lyubageorgieva** [comment]
US requiring TA sign off @adivardhan1000

**Comment by adivardhan1000** [comment]
Looks good to me
