### ISSUE TITLE
[US] Website Deployment

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#90]
As an application developer, I want to have access to a website explaining UInnovate, so that I can understand the tool offered by the UInnovate team.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |         Low             |           5         |

## Acceptance Criteria
- Ability to access the UInnovate website explaining the project

## Risks
TBD

## Tasks
- [ ] Meet with the Stakeholder to discuss the information to be displayed on the website and which template will be used
- [ ] Design a deployment system for: a website, documentation, test coverage reports, etc
- [ ] Deploy it from a github repository into a netlify instance
- [ ] Create the first simple iteration of the website explaining the project

**Comment by TheOrangeDuke** [comment]
Looks good to me!
Signing off!
