### ISSUE TITLE
[US] PostgREST API Testing and Documentation

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#91]
As an application configurator, I want to be able to test the content of the API calls, so that I can validate the functionality of the VMD.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |       Low              |        8           |

## Acceptance Criteria
- Ability to test the Usecase's API

## Risks
- Adding complexity to the VMD

## Tasks
- [x] Meeting with the Stakeholder
- [x] A big exploration of the Usecase's generated API, in order to design the Data Accessor URL builders inside the VMD.
- [x] Complete documentation of the API in Mkdocs.
- [x] Find a new framework for testing API calls (Postman may not be the route we wish to take, hence research possible testing options).
- [x] Writing tests alongside the current Usecase 1.

**Comment by GuardiansAscend** [comment]
Please see https://github.com/WillTrem/UInnovate/pull/298 for verifying what happened in this story, and if you have questions ask me :)
