### ISSUE TITLE
[US] Usecase Schema Name

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#92]
As a platform developer, I want to have a schema name that is appropriate for the Usecase, so that it better represents the application.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |          Low            |             2       |

## Acceptance Criteria
- The schema name changes are successfully reflected for the Usecase 1 and for any future Usecase/application

## Risks
TBD

## Tasks
- [x] Meeting with the Stakeholder
- [x] For the usecase, change the schema name to: ``app_rentals``
- [x] In docker, change the schema name to ``app_*``
- [x] Change the dockerfile, to make sure both schemas are picked up

**Comment by TheOrangeDuke** [comment]
Signing off!

**Comment by GuardiansAscend** [comment]
https://github.com/WillTrem/UInnovate/assets/61199167/b1d1e999-afb3-4c64-9654-7bcd33400e19
