### ISSUE TITLE
[US] List View Modal

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#93]
As an application user, I want to have a button on top of the table that opens a modal with the required fields, so that I can create new entities on the List View based on the columns that are required.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |          Low            |        4            |

## Acceptance Criteria
- Ability to view the "Add Entity" button
- Display the modal to add a new entity
- Once the entity is created, refresh the table

## Risks
- Adding complexity to the VMD

## Tasks
- [x] Add a button at the top of the List View Table to prompt the user to "Add {new entity}"
- [x] Display a modal for a user to create a new entity based on the columns that are required.
``COMMENT ON COLUMN table.column_one IS '{"reqOnCreate": true}';``
- [x] Refresh table after creation

## Sketch made by Stakeholder
<img width="541" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/e47ca27d-b9d5-4756-b8f8-f46ffee697ef">

## Additional Note
Dependent with US #94

**Comment by lyubageorgieva** [comment]
## Demo Video


https://github.com/WillTrem/UInnovate/assets/74876532/eb8a84b0-782b-4637-b8a5-14b45303c8d5

Related to PR #119

**Comment by TheOrangeDuke** [comment]
Looks good to me!
Can't wait to see it in action when the column properties will be created!
Signing off!
