### ISSUE TITLE
[US] Implement Stored Procedures and Fix Postgres Comments

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#94]
As a application developer, I want to some of the functionality of my database to run as stored procedures and comments, so that it is easier to observe and modify their behaviour.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |     Low              |           3         |

## Acceptance Criteria
- Ability to run some of the important functionality of the database through stored procedures
- Ability to read the comments on the columns of the use case database in json format

## Risks
- The Use case database is not properly readable by the VMD

## Tasks
- [x] Meeting with the Stakeholder to determine what stored procedures and further comment changes are needed
- [x] Perform any adjustments needed to the database from meeting
- [x] Create the necessary stored procedures to implement discussed
- [x] Adjust the column comments to JSON format, and add new comments as needed

## Additional Information
User story #93 has dependancies on some of the tasks in this story

**Comment by GuardiansAscend** [comment]
https://github.com/WillTrem/UInnovate/assets/61199167/b0799206-335f-4468-950f-c751c768be9e

**Comment by TheOrangeDuke** [comment]
Looks good!
Signing off!
