### ISSUE TITLE
[US] Create Use Case 2

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#96]
As a platform developer, I want to have a new use case, so that I can further test the funcionality of our platform.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |         Low             |          6          |

## Acceptance Criteria
- A new use case has been developed, with a corresponding schema and database
- Documentation of this use case has been developed, including API and functioanlity

## Risks
- Usecase does not follow the Stakeholder's expectations

## Tasks
- [x] Meeting with the Stakeholder to discuss the specifics of the new use case (preliminary ideas point to a Jira recreation)
- [x] Documenting use case requirements for the new use case
- [x] Documenting the domain model definition for the new use case
- [x] Creating an ER diagram of the new use case
- [x] Creating a creation script and population script, as well as running and testing the new database
- [ ] Exploring the generated API, and creating documentation regarding the important API calls

**Comment by witnick** [comment]
## Use case 2 Requirements

- Ticket Creation:
  - Users (customers) should be able to create new service tickets.
- Ticket Listing and Search:
  - Users should be able to view a list of their own tickets.
  - Agents and admins should be able to view and search all tickets.
  - Filtering options based on status, priority, and date should be available.
- Ticket Details:
  - Clicking on a ticket should display detailed information including status, comments, attachments, and history.
- Ticket Assignment:
  - Agents and admins should be able to assign tickets to themselves or other agents.
  - Notification to assigned agents when a ticket is assigned to them.
- Ticket Updates:
  - Users should be able to add comments and attachments to a ticket.
  - Agents should be able to change the status, priority, and other relevant details.
- Ticket Resolution:
  - Agents should have the ability to mark a ticket as resolved or closed.
  - Users should be notified when their ticket is resolved or closed.
- History and Audit Trail:
  - A log of all changes to a ticket (status changes, comments, assignments) should be maintained for a given ticket.
  - Admins and Agents should have access to an audit trail for all ticket-related activities.
- Notifications:
  - Users should receive notifications for ticket updates and resolutions.
  - Agents should be notified of new assigned tickets and updates.

**Comment by witnick** [comment]
## Use case digram
![UseCase2-service ticket-use-cases-drawio](https://github.com/WillTrem/UInnovate/assets/10947924/2cd7e5bc-c4ce-46ef-9cf0-f1ff80ede26a)

## ER diagram
![UseCase2-service-ticket-mgmt-db](https://github.com/WillTrem/UInnovate/assets/10947924/b1535f62-39a4-4707-bbb3-aa2ecd993c16)

**Comment by witnick** [comment]
##Updated ER diagram

![UseCase2-service-ticket-mgmt-db-v2](https://github.com/WillTrem/UInnovate/assets/10947924/24a3d55b-cfbf-4d0a-8bd2-bd9a59d8a3e9)

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/409b2bc5-e37e-4b6b-aebe-4f7576bf71be

**Comment by TheOrangeDuke** [comment]
Looks good to me!
Signing off!
