### ISSUE TITLE
[US] Lookup Display Table

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#97]
As an application user, I want to be able to view related entries in Lookup Tables directly from the List View, so that I can see all the related tables at the same time.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |          Medium            |       4             |

## Acceptance Criteria
- Ability to select which lookup table is relevant to which table from the Settings page
- Ability to save the configuration from the Settings page to be reflected directly on the List View
- Ability to display the lookup table

## Risks
- Adding complexity to the VMD

## Tasks
- [x] Meeting with Stakeholder
- [x] Add Lookup tables display (show related tables and filtered results underneath the row's properties)
- [x] Store tables in database to know which tables to show in detail view
- [x] Add a configuration parameter to be able to select which associated tables should be displayed in the details and how to query by URL 
- [x] Testing

**_This needs the VMD to be working_**

### From the Settings page
<img width="874" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/2da9b1ed-dbd8-4326-8176-6663455a3830">

### From the List View, in the side panel on row click of a table
<img width="567" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/8a370cee-9465-454a-b680-18bb5c4540f9">

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/d96b6125-8015-4fcc-9fac-9e569bd7f07b

**Comment by TheOrangeDuke** [comment]
Looking sharp! Signing off!
