### ISSUE TITLE
[US] PG_cron Install and Setup

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#98]
As a platform developer, I want to enable our platform to use the functionality of PG cron, so that I have a system in my platform that enables scheduled activities as a feature.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |        Medium          |           5         |

## Acceptance Criteria
- PG_cron is properly installed, and it is usable within the Docker container that has been setup
- A table exists for storing tasks and their triggers, so that scheduled activities can be triggered from the UI

## Risks
- PG_cron may be more complicated to setup properly than anticipated, leading to overhead

## Tasks
- [x] Research into PG_cron and how it is used
- [x] Meeting with the Stakeholder to discuss the needed functionality for scheduled activities
- [x] Installation and setup of PG_cron and cron jobs in the docker container
- [x] Creation and configuration of the task queue table
- [x] Creating the needed triggers in the front-end to create and activate cron jobs in the table

**Comment by tsitirides** [comment]
Install and setup:

1. Change to the directory of UInnovate
2. Run `docker compose build` from within the directory
3. open PG Admin (localhost:5000)
4. right click the innovate database
5. Press Query Tool
6. Run `CREATE EXTENSION pg_cron`
7. You should now see the cron schema with the tables job and job_run_details

**Comment by tsitirides** [comment]
https://github.com/WillTrem/UInnovate/assets/47327032/d51fe9ab-ec34-46f4-82cf-7d2b18ae12da

**Comment by TheOrangeDuke** [comment]
Looks good to me. 
Signing off.
