### ISSUE TITLE
[US] Editable Fields in the Details View

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#99]
As an application developer, I want to be able to edit the fields within the Details View, so that I can modify anything that needs modification.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |         Low             |           3         |

## Acceptance Criteria
- Ability to edit the fields on the details view and reflect the changes on save

## Risks
- Adding complexity to the VMD

## Tasks
- [x] Make the fields in the details view editable
- [x] On 'save' (create a save button) -> do a patch API call 
- [x] Retrieve the primary keys to see what needs to edited for proper API call
- [x] Testing
**_This needs the VMD to be working_**

**Comment by MaximeJoanisse** [comment]
Rough Design
![image](https://github.com/WillTrem/UInnovate/assets/92006009/9f4b16be-196d-420b-9487-8c6761e9ba73)

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/c1d67279-b51d-451f-874c-7bb5fb44f0e3

**Comment by TheOrangeDuke** [comment]
Looks good, singing off!
